import type { Argument, ClaimDigitalTwin, ClaimStage, ConfidenceProfile, Evidence, IssueDisposition, WhiteFinding } from './domain.ts';

export const CLAIM_PIPELINE: readonly ClaimStage[] = ['INGESTION','NORMALIZATION','IDENTITY','POLICY_LAW','EVIDENCE_CAUSATION','BUILDING_SCIENCE','ESTIMATE_INVOICE','RED_BLUE','WHITE','HUMAN_REVIEW','REPORT'];
export const ROLE_AGENTS = ['claim-intake','document-control','policy-intelligence','jurisdiction','causation','building-science','damage-classification','xactimate-estimating','line-item-forensics','invoice-forensics','water-mitigation','roofing','fire-smoke','contents','depreciation','overhead-profit','code-ordinance','pricing','dependency','evidence','timeline','claim-compliance','contractor-compliance','siu-anomaly','expert-report-critic','litigation','regulatory','human-review'] as const;

export function nextStage(current: ClaimStage): ClaimStage | null { const index = CLAIM_PIPELINE.indexOf(current); return index >= 0 && index < CLAIM_PIPELINE.length - 1 ? CLAIM_PIPELINE[index + 1] : null; }
export function canAdvance(stage: ClaimStage, twin: ClaimDigitalTwin): { ok: boolean; reasons: string[] } {
  const reasons: string[] = [];
  if (stage === 'POLICY_LAW' && !twin.policy) reasons.push('complete policy reconstruction is required before coverage analysis');
  if (stage === 'EVIDENCE_CAUSATION' && twin.evidence.length === 0) reasons.push('at least one source-bound evidence record is required');
  if (stage === 'WHITE' && twin.arguments.some((issue) => !issue.whiteTeam)) reasons.push('every issue requires a White Team finding');
  if (stage === 'HUMAN_REVIEW' && twin.arguments.some((issue) => issue.humanReview && !issue.whiteTeam)) reasons.push('escalated issues require documented neutral findings');
  return { ok: reasons.length === 0, reasons };
}
export function validateEvidence(evidence: Evidence[]): string[] { const errors: string[] = []; for (const item of evidence) { if (!item.evidenceId) errors.push('evidenceId required'); if (item.sourceStatus !== 'KNOWN') errors.push(`${item.evidenceId}: source is not verified`); if (item.supports.length === 0 && item.contradicts.length === 0) errors.push(`${item.evidenceId}: must support or contradict a proposition`); } return errors; }
export function whiteTeam(issue: Argument): WhiteFinding { const supported = issue.evidenceFor.filter((id) => !issue.evidenceAgainst.includes(id)); const disposition: IssueDisposition = supported.length === 0 ? 'DOCUMENTATION_DEFICIENT' : issue.carrierPosition && issue.contractorPosition ? 'PARTIALLY_SUPPORTED' : 'MISSING'; return { finding: disposition === 'PARTIALLY_SUPPORTED' ? 'Both positions contain support; resolve only the supported component.' : 'The record is insufficient for a reliable conclusion.', disposition, rationale: 'Neutral finding is limited to source-bound evidence and does not infer missing policy, work, or pricing facts.', supportedEvidence: supported, unresolvedFact: 'Whether the claimed operation was necessary and covered on the loss facts.', additionalEvidenceNeeded: ['policy provision and endorsement', 'contemporaneous work/equipment records', 'line-specific reviewer basis'] }; }
export function confidenceProfile(input: Omit<ConfidenceProfile, 'overall'>): ConfidenceProfile { const critical = Math.min(input.fact, input.policy, input.legal, input.causation); const overall = critical >= 85 ? 'HIGH' : critical >= 60 ? 'MEDIUM' : critical >= 30 ? 'LOW' : 'UNDETERMINED'; return { ...input, overall }; }
export function policyFirstGuard(twin: ClaimDigitalTwin): string[] { const errors: string[] = []; if (!twin.policy) errors.push('BLOCK: policy/declarations/forms/endorsements required before estimate conclusions'); if (twin.claim.status !== 'KNOWN') errors.push('BLOCK: claim identity is not verified'); return errors; }
