import test from 'node:test';
import assert from 'node:assert/strict';
import { selectFloridaStatutoryVersion, verifyHistoricalVersion, type FloridaStatutoryVersion } from '../florida/historical.ts';
import { analyzeDCAConflict } from '../florida/conflicts.ts';
import { createOpinionSnapshot, verifyOpinionSnapshot, type FloridaCaseOpinion } from '../florida/opinions.ts';
import { ingestClaimPolicy, policyDocumentHash } from '../policy/ingestion.ts';

const v1:FloridaStatutoryVersion={authorityId:'FL-626.9744',citation:'Fla. Stat. § 626.9744',versionId:'V1',validFrom:'2004-10-01',validTo:'2025-01-01',sourceSnapshotId:'S1',sourceUrl:'https://www.leg.state.fl.us/source',operativeText:'historical text',amendedBy:['A1'],supersededBy:['V2'],applicabilityNotes:['historical applicability requires verification'],effectiveDateVerified:true,applicabilityVerified:true,verified:true};
const v2={...v1,versionId:'V2',validFrom:'2025-01-01',validTo:null,sourceSnapshotId:'S2',supersededBy:[],operativeText:'current text'};
test('Florida statutory selection uses date of loss and preserves historical versions',()=>{assert.equal(selectFloridaStatutoryVersion([v1,v2],{policyInception:null,policyRenewal:null,endorsementEffectiveDate:null,dateOfLoss:'2024-12-31',claimNotice:null,supplementDate:null,appraisalDemand:null,preSuitNotice:null,suitFiling:null,judgment:null})?.versionId,'V1');assert.equal(selectFloridaStatutoryVersion([v1,v2],{policyInception:null,policyRenewal:null,endorsementEffectiveDate:null,dateOfLoss:'2026-03-15',claimNotice:null,supplementDate:null,appraisalDemand:null,preSuitNotice:null,suitFiling:null,judgment:null})?.versionId,'V2');assert.deepEqual(verifyHistoricalVersion(v1),[]);});
test('opinion verification requires official snapshot and pinpoint',()=>{const opinion:FloridaCaseOpinion={caseId:'CASE-1',caseName:'Example',citation:'100 So. 3d 1',court:'THIRD_DCA',district:'Third',decisionDate:'2020-01-01',issueCodes:['MATCHING'],policyLanguage:['like kind and quality'],materialFacts:['siding'],proceduralPosture:'appeal',holding:'matching holding',dicta:[],pinpoints:['p. 4'],subsequentHistory:[],negativeTreatment:[],statutoryDependency:['626.9744'],policyDependency:['policy wording'],currentStatus:'CANDIDATE',verificationStatus:'UNVERIFIED',snapshotId:null};const snapshot=createOpinionSnapshot({snapshotId:'S-CASE-1',caseId:'CASE-1',sourceUrl:'https://www.3dca.flcourts.org/opinion.pdf',content:'p. 4 matching holding',retrievedAt:'2026-09-01',officialSource:true});assert.deepEqual(verifyOpinionSnapshot(snapshot,{...opinion,snapshotId:snapshot.snapshotId}),[]);});
test('DCA conflict analyzer refuses to merge different holdings',()=>{const base:FloridaCaseOpinion={caseId:'A',caseName:'A',citation:'1',court:'THIRD_DCA',district:'Third',decisionDate:'2020-01-01',issueCodes:['MATCHING'],policyLanguage:[],materialFacts:[],proceduralPosture:'appeal',holding:'requires adjoining replacement',dicta:[],pinpoints:['p. 1'],subsequentHistory:[],negativeTreatment:[],statutoryDependency:[],policyDependency:[],currentStatus:'VERIFIED',verificationStatus:'VERIFIED',snapshotId:'S'};const conflict=analyzeDCAConflict([base,{...base,caseId:'B',court:'FOURTH_DCA',district:'Fourth',holding:'does not require adjoining replacement'}],'MATCHING');assert.equal(conflict.status,'POTENTIAL_CONFLICT');assert.equal(conflict.humanReviewRequired,true);});
test('policy ingestion requires actual declarations and complete form metadata',()=>{const docs=[{documentId:'D',filename:'dec.pdf',sha256:policyDocumentHash('dec'),documentType:'DECLARATIONS' as const,text:'policy',formId:null,edition:null,effectiveFrom:'2025-01-01',effectiveTo:null,sourcePageRefs:['1']},{documentId:'P',filename:'ho3.pdf',sha256:policyDocumentHash('form'),documentType:'POLICY_FORM' as const,text:'loss settlement',formId:'HO-3',edition:'2024',effectiveFrom:'2025-01-01',effectiveTo:null,sourcePageRefs:['20']}];const result=ingestClaimPolicy(docs,'2026-03-15');assert.equal(result.ready,true);assert.equal(result.policyForm,'HO-3');assert.equal(result.policyEdition,'2024');assert.ok(result.policyHash);});
