import test from 'node:test';
import assert from 'node:assert/strict';
import { analyzeFloridaMatching, comparePolicyToCase, fingerprintPolicyClause, type PolicyMatchingContext } from '../policy/matching.ts';
import { HumanLegalReviewQueue } from '../review/human.ts';

const context:PolicyMatchingContext={claimId:'C-1',jurisdiction:'FL',dateOfLoss:'2026-03-15',policyForm:'HO-3',policyEdition:'2024',policyHash:'a'.repeat(64),coverageProvisions:['Coverage A'],lossSettlementProvisions:['repair or replace'],valuationProvisions:['replacement cost'],repairReplaceProvisions:['like kind and quality'],pairSetProvisions:[],matchingRelatedEndorsements:[],roofEndorsements:[],cosmeticEndorsements:[],ordinanceLawEndorsements:[],component:'siding',material:'fiber cement',directlyDamagedQuantity:420,requestedReplacementQuantity:1800,exactMatchAvailable:false,reasonableMatchAvailable:false,technicalRepairFeasible:false,appearanceDifference:'visible',lineOfSight:true,facts:['covered wind damage'],evidenceRefs:['PHOTO-1'],legalAuthorityRefs:['FL-STAT-626.9744-2026'],humanReview:false};
test('policy matching is policy and fact dependent, not state boolean',()=>{const result=analyzeFloridaMatching(context,true,true);assert.equal(result.status,'MATCHING_POTENTIALLY_REQUIRED');assert.equal(result.xactimateConstraint.directDamage,420);assert.ok(result.technicalQuestions.length===0);});
test('policy/case comparator flags materially different wording',()=>{const result=comparePolicyToCase('we will repair or replace with like kind and quality','we pay direct physical loss only', {form:'HO-3',edition:'2024'},{form:'CP',edition:'2010'});assert.equal(result.matchType,'MATERIALLY_DIFFERENT');assert.equal(result.requiresHumanReview,true);assert.ok(fingerprintPolicyClause('like kind and quality','Loss Settlement','HO-3','2024').fingerprintId);});
test('human review queue stores surgical policy/case dependency decisions',()=>{const queue=new HumanLegalReviewQueue();queue.enqueue({reviewId:'REV-1',claimId:'C-1',jurisdiction:'FL',issue:'MATCHING',question:'Does the endorsement alter adjoining-area matching?',policyText:['endorsement text'],policyDifferences:['case lacks endorsement'],candidateAuthorities:['FL-STAT-626.9744-2026'],candidateRules:['FL-MATCHING-CANDIDATE'],redTeam:{},blueTeam:{},whiteTeam:{},conflicts:[],recommendedResolution:'review endorsement interaction',confidence:{policy:60},reviewerType:'PROPERTY_COVERAGE_COUNSEL',status:'PENDING',scope:'CLAIM_ONLY'});queue.decide({reviewId:'REV-1',action:'APPROVED_WITH_LIMITATION',reviewer:'human-1',timestamp:'2026-09-01T00:00:00Z',reason:'approved only for this claim',authorityReliedUpon:['FL-STAT-626.9744-2026'],scope:'CLAIM_ONLY'});assert.equal(queue.list()[0].status,'APPROVED_WITH_LIMITATION');});
