import test from 'node:test';
import assert from 'node:assert/strict';
import { remediateSixGates, type ResearchAdapter } from '../research/remediation.ts';
import { SourceSnapshotStore } from '../sources/store.ts';
import type { LegalAuthority, LegalProposition, CompiledLegalRule } from '../types/index.ts';

const authority: LegalAuthority = { authorityId: 'FL-TEST-1', jurisdiction: 'FL', authorityType: 'STATE_STATUTE', title: 'Test official statute', citation: 'Fla. Stat. § 000.001', officialSourceUrl: 'https://www.leg.state.fl.us/test', retrievedAt: '2026-09-01', contentHash: 'a'.repeat(64), amends: [], repeals: [], interprets: [], negativeTreatment: [], verificationStatus: 'VERIFIED' };
const proposition: LegalProposition = { propositionId: 'P-1', authorityId: authority.authorityId, issueCode: 'MATCHING', jurisdiction: 'FL', ruleText: 'verified proposition', normalizedRule: 'verified proposition', holdingOrDicta: 'UNKNOWN', mandatoryOrPermissive: 'MANDATORY', partyBearingBurden: 'UNKNOWN', standard: 'UNKNOWN', conditions: [], exceptions: [], remedies: [], policyLanguageDependency: [], factDependency: [], temporal: { validFrom: '2020-01-01', validTo: null, systemFrom: '2026-09-01', systemTo: null }, pinpointCitation: '§ 000.001', verificationStatus: 'VERIFIED', confidence: 90 };
const rule: CompiledLegalRule = { ruleId: 'R-1', jurisdiction: 'FL', issue: 'MATCHING', validity: proposition.temporal, priority: 1, if: { all: [], any: [], not: [] }, then: { classification: 'FACT_DEPENDENT', effects: [] }, exceptions: [], authorityRefs: [authority.authorityId], policyDependencies: [], factDependencies: [], confidence: 90, humanReviewConditions: [], status: 'AUTHORITY_VERIFIED' };

function adapter(overrides: Partial<ResearchAdapter> = {}): ResearchAdapter {
  return { discover: async () => ['https://www.leg.state.fl.us/test'], retrieve: async (url) => ({ url, content: 'official source content', retrievedAt: '2026-09-01', sourceType: 'STATE_STATUTE', official: true }), extractAuthorities: async () => [authority], extractPropositions: async () => [proposition], compile: async () => [rule], redBlueWhite: async () => ({ passed: true, blockers: [] }), verifyCitations: async () => ({ passed: true, blockers: [] }), validateTemporal: async () => ({ passed: true, blockers: [] }), resolveConflicts: async () => ({ criticalConflicts: 0, blockers: [] }), runTests: async () => ({ passed: true, blockers: [] }), ...overrides };
}

test('six-gate remediation activates only after every gate passes', async () => { const result = await remediateSixGates({ jurisdiction: 'FL', issue: 'MATCHING', effectiveDate: '2026-03-15' }, adapter(), new SourceSnapshotStore()); assert.equal(result.status, 'COMPLETE_VERIFIED'); assert.equal(result.activated.length, 1); assert.deepEqual(result.gates.map((gate) => gate.status), ['PASSED', 'PASSED', 'PASSED', 'PASSED', 'PASSED', 'PASSED']); });
test('six-gate remediation preserves RESEARCH_REQUIRED when authority verification fails', async () => { const result = await remediateSixGates({ jurisdiction: 'FL', issue: 'MATCHING', effectiveDate: '2026-03-15' }, adapter({ extractAuthorities: async () => [{ ...authority, verificationStatus: 'UNVERIFIED' }] }), new SourceSnapshotStore()); assert.equal(result.status, 'RESEARCH_REQUIRED'); assert.equal(result.activated.length, 0); assert.ok(result.blockers.includes('authority verification')); });
test('human-review-required rules are queued and not activated without approval', async () => { let queued = false; const result = await remediateSixGates({ jurisdiction: 'FL', issue: 'MATCHING', effectiveDate: '2026-03-15' }, adapter({ compile: async () => [{ ...rule, humanReviewConditions: ['ambiguous policy wording'] }] }), new SourceSnapshotStore(), { enqueue: async () => { queued = true; } }); assert.equal(queued, true); assert.equal(result.status, 'COMPLETE_WITH_REVIEW'); assert.equal(result.activated.length, 0); });
