CREATE TABLE IF NOT EXISTS provider_reviews (provider_id TEXT PRIMARY KEY, lifecycle TEXT NOT NULL CHECK (lifecycle IN ('DISCOVERED','SECURITY_REVIEW','TERMS_REVIEW','SCHEMA_TEST','DATA_QUALITY_TEST','AUTHORITY_TEST','APPROVED','ACTIVE')), terms_reviewed INTEGER NOT NULL DEFAULT 0 CHECK (terms_reviewed IN (0,1)), schema_validated INTEGER NOT NULL DEFAULT 0 CHECK (schema_validated IN (0,1)), authority_validated INTEGER NOT NULL DEFAULT 0 CHECK (authority_validated IN (0,1)), security_reviewed INTEGER NOT NULL DEFAULT 0 CHECK (security_reviewed IN (0,1)), approved_by TEXT, approved_at TEXT, notes_json TEXT NOT NULL DEFAULT '[]', updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS provider_coverage (provider_id TEXT NOT NULL, coverage_id TEXT NOT NULL, name TEXT NOT NULL, country TEXT NOT NULL, court_level TEXT, source_scope TEXT NOT NULL, PRIMARY KEY(provider_id, coverage_id));
CREATE TABLE IF NOT EXISTS provider_review_evidence (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id TEXT NOT NULL, gate TEXT NOT NULL, passed INTEGER NOT NULL CHECK (passed IN (0,1)), reviewer TEXT NOT NULL, evidence_url TEXT, evidence_hash TEXT, notes_json TEXT NOT NULL DEFAULT '[]', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS provider_activation_events (id INTEGER PRIMARY KEY AUTOINCREMENT, provider_id TEXT NOT NULL, event_type TEXT NOT NULL, actor TEXT NOT NULL, details_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_provider_reviews_lifecycle ON provider_reviews(lifecycle);
CREATE INDEX IF NOT EXISTS idx_provider_evidence_provider ON provider_review_evidence(provider_id, gate, created_at);
INSERT OR IGNORE INTO providers (id, display_name, jurisdictions_json, capabilities_json, status) VALUES
('courtlistener', 'CourtListener', '["US"]', '{}', 'unknown'), ('recap', 'RECAP', '["US-FEDERAL"]', '{}', 'unknown'), ('juriscraper', 'Juriscraper', '["US"]', '{}', 'unknown'), ('worldlii', 'WorldLII', '["GLOBAL"]', '{}', 'unknown'), ('commonlii', 'CommonLII', '["COMMONWEALTH"]', '{}', 'unknown'), ('asianlii', 'AsianLII', '["ASIA"]', '{}', 'unknown'), ('paclii', 'PacLII', '["PACIFIC"]', '{}', 'unknown'), ('hklii', 'HKLII', '["HK"]', '{}', 'unknown'), ('kenyalaw', 'Kenya Law', '["KE"]', '{}', 'unknown'), ('canlii', 'CanLII', '["CA"]', '{}', 'unknown'), ('eurlex', 'EUR-Lex', '["EU"]', '{}', 'unknown'), ('curia', 'CURIA', '["EU-CJEU"]', '{}', 'unknown'), ('hudoc', 'HUDOC', '["ECHR"]', '{}', 'unknown'), ('icj', 'ICJ', '["INTL-ICJ"]', '{}', 'unknown'), ('icc', 'ICC', '["INTL-ICC"]', '{}', 'unknown'), ('icsid', 'ICSID', '["INTL-ICSID"]', '{}', 'unknown'), ('pca', 'PCA', '["INTL-PCA"]', '{}', 'unknown'), ('itlos', 'ITLOS', '["INTL-ITLOS"]', '{}', 'unknown'), ('bailii', 'BAILII', '["GB","IE"]', '{}', 'unknown'), ('austlii', 'AustLII', '["AU"]', '{}', 'unknown'), ('nzlii', 'NZLII', '["NZ"]', '{}', 'unknown'), ('saflii', 'SAFLII', '["ZA"]', '{}', 'unknown');
INSERT OR IGNORE INTO provider_reviews (provider_id, lifecycle) SELECT id, 'DISCOVERED' FROM providers;
INSERT OR IGNORE INTO provider_coverage (provider_id, coverage_id, name, country, court_level, source_scope) VALUES
('courtlistener', 'US-FEDERAL', 'United States federal courts', 'US', NULL, 'repository'), ('courtlistener', 'US-STATE', 'United States state courts', 'US', NULL, 'repository'),
('juriscraper', 'US-FEDERAL', 'United States federal courts', 'US', NULL, 'aggregator'), ('juriscraper', 'US-SCOTUS', 'U.S. Supreme Court', 'US', 'apex', 'aggregator'), ('juriscraper', 'US-CA2', 'U.S. Court of Appeals for the Second Circuit', 'US', 'appellate', 'aggregator'), ('juriscraper', 'US-SDNY', 'U.S. District Court for the Southern District of New York', 'US', 'trial', 'aggregator'), ('juriscraper', 'US-STATE-SUPREME', 'U.S. state courts of last resort', 'US', 'apex', 'aggregator'), ('juriscraper', 'US-STATE-APPELLATE', 'U.S. state appellate courts', 'US', 'appellate', 'aggregator'),
('worldlii', 'GLOBAL', 'Global legal-information institute discovery', 'GLOBAL', NULL, 'discovery'), ('commonlii', 'COMMONWEALTH', 'Commonwealth jurisdictions', 'COMMONWEALTH', NULL, 'aggregator'), ('asianlii', 'ASIA', 'Asian jurisdictions', 'ASIA', NULL, 'aggregator'), ('paclii', 'PACIFIC', 'Pacific Island jurisdictions', 'PACIFIC', NULL, 'aggregator'),
('hklii', 'HK', 'Hong Kong', 'HK', NULL, 'repository'), ('hklii', 'HK-CFA', 'Hong Kong Court of Final Appeal', 'HK', 'apex', 'repository'), ('hklii', 'HK-HC', 'Hong Kong High Court', 'HK', 'trial', 'repository'), ('hklii', 'HK-DC', 'Hong Kong District Court', 'HK', 'trial', 'repository'),
('kenyalaw', 'KE', 'Kenya', 'KE', NULL, 'official'), ('kenyalaw', 'KE-SC', 'Supreme Court of Kenya', 'KE', 'apex', 'official'), ('kenyalaw', 'KE-CA', 'Court of Appeal of Kenya', 'KE', 'appellate', 'official'), ('kenyalaw', 'KE-HC', 'High Court of Kenya', 'KE', 'trial', 'official'), ('kenyalaw', 'KE-ELC', 'Environment and Land Court of Kenya', 'KE', 'trial', 'official'), ('kenyalaw', 'KE-ELRC', 'Employment and Labour Relations Court of Kenya', 'KE', 'trial', 'official');
