import { z } from 'zod';

export const legalSearchQuerySchema = z.object({
  text: z.string().trim().min(1).max(2000), jurisdiction: z.array(z.string()).optional(), country: z.array(z.string()).optional(), court: z.array(z.string()).optional(), courtLevel: z.array(z.string()).optional(), caseName: z.string().optional(), docketNumber: z.string().optional(), neutralCitation: z.string().optional(), reporterCitation: z.string().optional(), judge: z.array(z.string()).optional(), party: z.array(z.string()).optional(), statute: z.array(z.string()).optional(), regulation: z.array(z.string()).optional(), proceduralPosture: z.array(z.string()).optional(), legalIssue: z.array(z.string()).optional(), dateFrom: z.string().date().optional(), dateTo: z.string().date().optional(), bindingOnly: z.boolean().optional(), publishedOnly: z.boolean().optional(), includeDockets: z.boolean().optional(), includeOpinions: z.boolean().optional(), includeFilings: z.boolean().optional(), semanticSearch: z.boolean().optional(), citationSearch: z.boolean().optional(), limit: z.number().int().min(1).max(100).default(20)
});
export const researchSchema = z.object({ query: z.string().trim().min(1).max(2000), mode: z.enum(['QUICK','STANDARD','DEEP','LITIGATION','APPELLATE','GLOBAL','CITATION_VERIFY','ADVERSE_AUTHORITY','DOCKET','STATUTORY','REGULATORY']).default('STANDARD'), jurisdiction: z.array(z.string()).optional(), depth: z.number().int().min(1).max(10).default(2) });
export const citationSchema = z.object({ citation: z.string().trim().min(2).max(300) });
export const providerReviewSchema = z.object({ gate: z.enum(['termsReviewed', 'schemaValidated', 'authorityValidated', 'securityReviewed']), passed: z.boolean(), evidenceUrl: z.string().url().max(2000).optional(), evidenceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional(), notes: z.array(z.string().max(1000)).max(20).optional(), reviewer: z.string().trim().min(1).max(200) }).superRefine((value, ctx) => { if (value.passed && !value.evidenceUrl && !value.evidenceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['evidenceUrl'], message: 'Evidence URL or SHA-256 evidence hash is required when a gate passes.' }); });
export const providerActivationSchema = z.object({ approver: z.string().trim().min(1).max(200), notes: z.array(z.string().max(1000)).max(20).optional() });
export const judgeObservationSchema = z.object({ judgeId: z.string().trim().min(1).max(200), matterId: z.string().trim().max(200).optional(), sourceId: z.string().uuid().optional(), dimension: z.enum(['procedure','discovery','evidence','case-management','sanctions','hearing','appellate-safety']), proposition: z.string().trim().min(1).max(1000), value: z.string().trim().min(1).max(2000), sourceClass: z.enum(['official-procedure','published-order','published-opinion','docket','secondary','user-record']), sourceUrl: z.string().url().max(2000).optional(), sourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional(), observedAt: z.string().date(), confidence: z.number().min(0).max(1), status: z.enum(['VERIFIED','UNVERIFIED','DISPUTED']).default('UNVERIFIED') });
export const judgePredictionSchema = z.object({ judgeId: z.string().trim().min(1).max(200), matterId: z.string().trim().max(200).optional(), issue: z.string().trim().min(1).max(2000) });
export const judgeProfileReviewSchema = z.object({ predictionId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['APPROVED','REJECTED']), notes: z.string().trim().min(1).max(2000) });
export const judgeObservationReviewSchema = z.object({ observationId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['VERIFIED','DISPUTED']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (value.decision === 'VERIFIED' && !value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Verification evidence URL or SHA-256 hash is required.' }); });
export const judgeSourcePayloadSchema = z.object({ matterId: z.string().trim().max(200).optional(), sourceClass: z.enum(['official-procedure','published-order','published-opinion','docket','secondary','user-record']), sourceUrl: z.string().url().max(2000).optional(), title: z.string().trim().max(500).optional(), effectiveDate: z.string().date().optional(), content: z.string().max(2_000_000).optional() }).refine((v) => v.sourceUrl || v.content, { message: 'sourceUrl or content is required', path: ['sourceUrl'] });
export const judgeSourceSchema = judgeSourcePayloadSchema.innerType().extend({ judgeId: z.string().trim().min(1).max(200) }).refine((v) => v.sourceUrl || v.content, { message: 'sourceUrl or content is required', path: ['sourceUrl'] });
export const officialJudgeSourceSchema = z.object({ url: z.string().url().max(2000), sourceClass: z.enum(['official-procedure','published-order','published-opinion']), title: z.string().trim().max(500).optional(), effectiveDate: z.string().date().optional() });
export const judgeSourceReviewSchema = z.object({ sourceId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['VERIFIED','REJECTED']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (value.decision === 'VERIFIED' && !value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Independent evidence URL or SHA-256 evidence hash is required.' }); });
export const judgeIdentitySchema = z.object({ judgeId: z.string().trim().min(1).max(200), judgeName: z.string().trim().min(1).max(200), court: z.string().trim().min(1).max(300), county: z.string().trim().max(200).optional(), judicialCircuit: z.string().trim().max(200).optional(), division: z.string().trim().max(200).optional(), assignment: z.string().trim().max(500).optional(), profileAsOf: z.string().date(), status: z.enum(['CURRENT','STALE','NEEDS_VERIFICATION']) });
export const adversarialReviewSchema = z.object({ issue: z.string().trim().min(1).max(2000), matterId: z.string().trim().max(200).optional() });
export const adversarialReviewDecisionSchema = z.object({ reviewId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['APPROVED','REJECTED']), notes: z.string().trim().min(1).max(2000) });
export const judgeCaseObservationSchema = z.object({ judgeId: z.string().trim().min(1).max(200), matterId: z.string().trim().max(200).optional(), caseId: z.string().trim().min(1).max(300), court: z.string().trim().min(1).max(300), division: z.string().trim().max(200).optional(), caseType: z.string().trim().max(200).optional(), proceduralPosture: z.string().trim().min(1).max(1000), issueClass: z.string().trim().min(1).max(500), motionType: z.string().trim().max(300).optional(), requestedRelief: z.string().trim().max(1000).optional(), ruling: z.string().trim().min(1).max(1000), reasons: z.string().trim().max(4000).optional(), comparabilityScore: z.number().min(0).max(1), sourceId: z.string().uuid().optional() });
export const judgeCaseObservationReviewSchema = z.object({ observationId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['VERIFIED','DISPUTED']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (value.decision === 'VERIFIED' && !value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Verification evidence URL or SHA-256 hash is required.' }); });
export const matterSchema = z.object({ matterId: z.string().trim().min(1).max(200), caseNumber: z.string().trim().max(200).optional(), court: z.string().trim().max(300).optional(), county: z.string().trim().max(200).optional(), circuit: z.string().trim().max(200).optional(), division: z.string().trim().max(200).optional(), judgeId: z.string().trim().max(200).optional(), status: z.enum(['ACTIVE','CLOSED','ARCHIVED']).default('ACTIVE') });
export const proceduralEventSchema = z.object({ eventType: z.string().trim().min(1).max(200), eventDate: z.string().date(), sourceId: z.string().uuid().optional(), status: z.enum(['UNVERIFIED','VERIFIED','DISPUTED']).default('UNVERIFIED'), payload: z.record(z.unknown()).default({}) });
export const discoveryObjectSchema = z.object({ kind: z.enum(['INTERROGATORY','REQUEST_FOR_PRODUCTION','REQUEST_FOR_ADMISSION','DEPOSITION','MOTION_TO_COMPEL','RESPONSE','ORDER','OTHER']), requestNumber: z.string().trim().max(100).optional(), exactText: z.string().max(10000).optional(), responseText: z.string().max(10000).optional(), objectionText: z.string().max(10000).optional(), servedAt: z.string().date().optional(), responseDue: z.string().date().optional(), respondedAt: z.string().date().optional(), productionStatus: z.enum(['UNKNOWN','NOT_PRODUCED','PARTIAL','PRODUCED','NO_RESPONSIVE_DOCUMENTS','PRIVILEGE_REVIEW']).default('UNKNOWN'), sourceId: z.string().uuid().optional(), status: z.enum(['UNVERIFIED','VERIFIED','DISPUTED']).default('UNVERIFIED') });
export const recordReviewSchema = z.object({ reviewer: z.string().trim().min(1).max(200), decision: z.enum(['VERIFIED','DISPUTED']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (value.decision === 'VERIFIED' && !value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Independent evidence URL or SHA-256 evidence hash is required.' }); });
export const filingArtifactSchema = z.object({ kind: z.string().trim().min(1).max(200), content: z.string().max(2_000_000).optional() });
export const filingAdvanceSchema = z.object({ nextStatus: z.enum(['FACT_CHECK','AUTHORITY_CHECK','RED_TEAM','BLUE_TEAM','PROCEDURAL_CHECK','EXHIBIT_CHECK','RELIEF_CHECK','HUMAN_REVIEW_REQUIRED','READY_TO_FILE','BLOCKED']), blockedReasons: z.array(z.string().trim().min(1).max(1000)).max(20).default([]), evidenceIds: z.array(z.string().trim().regex(/^(source|event|discovery|authority|adversarial|prediction):.+$/, 'Evidence references must use a supported type prefix.').max(300)).max(50).default([]), humanConfirmed: z.boolean().default(false), reviewer: z.string().trim().min(1).max(200).optional() }).superRefine((value, ctx) => { if (value.nextStatus !== 'BLOCKED' && value.nextStatus !== 'READY_TO_FILE' && value.evidenceIds.length === 0) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['evidenceIds'], message: 'Evidence or review-artifact IDs are required for every substantive filing gate.' }); if (value.nextStatus === 'READY_TO_FILE' && (!value.humanConfirmed || !value.reviewer)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['humanConfirmed'], message: 'A named human reviewer and confirmation are required before READY_TO_FILE.' }); });
export const authorityRecordSchema = z.object({ matterId: z.string().trim().max(200).optional(), name: z.string().trim().min(1).max(500), citation: z.string().trim().min(1).max(500), authorityType: z.enum(['RULE','STATUTE','CASE','ADMINISTRATIVE_ORDER','JUDGE_PROCEDURE','SECONDARY']), court: z.string().trim().max(300).optional(), year: z.number().int().min(1700).max(2200).optional(), proposition: z.string().trim().max(4000).optional(), sourceId: z.string().uuid().optional() });
export const authorityReviewSchema = z.object({ authorityId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['VERIFIED','NEGATIVE','CONFLICTING','SUPERSEDED']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (!value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Independent evidence URL or SHA-256 evidence hash is required for every authority decision.' }); });
export const authorityEdgeSchema = z.object({ fromAuthorityId: z.string().uuid(), toAuthorityId: z.string().uuid(), relationship: z.enum(['SUPERSEDES','LIMITS','DISTINGUISHES','NEGATIVE_TREATMENT','CONFLICTS_WITH']), evidenceNote: z.string().trim().min(1).max(2000), sourceId: z.string().uuid().optional() });
export const authorityEdgeReviewSchema = z.object({ edgeId: z.string().uuid(), reviewer: z.string().trim().min(1).max(200), decision: z.enum(['VERIFIED','DISPUTED']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (!value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Independent evidence URL or SHA-256 evidence hash is required.' }); });
export type JudgeObservationInput = z.infer<typeof judgeObservationSchema>;
export type LegalSearchInput = z.infer<typeof legalSearchQuerySchema>;
export const judgeIdentityReviewSchema = z.object({ reviewer: z.string().trim().min(1).max(200), decision: z.enum(['CURRENT','STALE','NEEDS_VERIFICATION']), notes: z.string().trim().min(1).max(2000), verificationSourceUrl: z.string().url().max(2000).optional(), verificationSourceHash: z.string().regex(/^[a-f0-9]{64}$/i).optional() }).superRefine((value, ctx) => { if (value.decision !== 'NEEDS_VERIFICATION' && !value.verificationSourceUrl && !value.verificationSourceHash) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['verificationSourceUrl'], message: 'Independent evidence URL or SHA-256 hash is required.' }); });
