import type { Env, ProviderLifecycle, ProviderReview, ProviderReviewGate, ProviderReviewRecord } from '../types';

const inactive: ProviderReview = { lifecycle: 'DISCOVERED', termsReviewed: false, schemaValidated: false, authorityValidated: false, securityReviewed: false, notes: ['No D1 approval record exists; provider is fail-closed.'] };
const stageFor = (review: ProviderReview): ProviderLifecycle => { if (!review.termsReviewed) return 'DISCOVERED'; if (!review.schemaValidated) return 'SCHEMA_TEST'; if (!review.authorityValidated) return 'AUTHORITY_TEST'; if (!review.securityReviewed) return 'SECURITY_REVIEW'; return 'APPROVED'; };
const asBool = (value: unknown): boolean => value === true || value === 1 || value === '1' || value === 'true';
const rowToReview = (row: Record<string, unknown>): ProviderReviewRecord => ({ providerId: String(row.provider_id), lifecycle: row.lifecycle as ProviderLifecycle, termsReviewed: asBool(row.terms_reviewed), schemaValidated: asBool(row.schema_validated), authorityValidated: asBool(row.authority_validated), securityReviewed: asBool(row.security_reviewed), approvedBy: row.approved_by ? String(row.approved_by) : undefined, approvedAt: row.approved_at ? String(row.approved_at) : undefined, updatedAt: row.updated_at ? String(row.updated_at) : undefined, notes: row.notes_json ? JSON.parse(String(row.notes_json)) as string[] : [] });

export async function loadProviderReviews(env: Env): Promise<Map<string, ProviderReview>> { const rows = await env.DB.prepare('SELECT * FROM provider_reviews').all<Record<string, unknown>>(); return new Map(rows.results.map((row) => { const review = rowToReview(row); return [review.providerId, review] as const; })); }
export function inactiveReview(): ProviderReview { return { ...inactive, notes: [...(inactive.notes ?? [])] }; }

export async function recordReviewGate(env: Env, providerId: string, gate: ProviderReviewGate, passed: boolean, reviewer: string, evidenceUrl?: string, evidenceHash?: string, notes: string[] = []): Promise<ProviderReviewRecord> { const currentRows = await env.DB.prepare('SELECT * FROM provider_reviews WHERE provider_id = ?').bind(providerId).all<Record<string, unknown>>(); const current = currentRows.results[0] ? rowToReview(currentRows.results[0]) : { providerId, ...inactiveReview() }; const next: ProviderReviewRecord = { ...current, [gate]: passed, lifecycle: 'DISCOVERED', updatedAt: new Date().toISOString(), notes: [...new Set([...(current.notes ?? []).filter((note) => !note.startsWith(`${gate}:`)), `${gate}: ${passed ? 'passed' : 'failed'}`, ...notes])] }; next.lifecycle = stageFor(next); await env.DB.batch([env.DB.prepare('INSERT INTO provider_reviews (provider_id, lifecycle, terms_reviewed, schema_validated, authority_validated, security_reviewed, approved_by, approved_at, notes_json, updated_at) VALUES (?, ?, ?, ?, ?, ?, NULL, NULL, ?, CURRENT_TIMESTAMP) ON CONFLICT(provider_id) DO UPDATE SET lifecycle=excluded.lifecycle, terms_reviewed=excluded.terms_reviewed, schema_validated=excluded.schema_validated, authority_validated=excluded.authority_validated, security_reviewed=excluded.security_reviewed, approved_by=NULL, approved_at=NULL, notes_json=excluded.notes_json, updated_at=CURRENT_TIMESTAMP').bind(providerId, next.lifecycle, next.termsReviewed ? 1 : 0, next.schemaValidated ? 1 : 0, next.authorityValidated ? 1 : 0, next.securityReviewed ? 1 : 0, JSON.stringify(next.notes ?? [])), env.DB.prepare('INSERT INTO provider_review_evidence (provider_id, gate, passed, reviewer, evidence_url, evidence_hash, notes_json) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(providerId, gate, passed ? 1 : 0, reviewer, evidenceUrl ?? null, evidenceHash ?? null, JSON.stringify(notes))]); await env.DB.prepare('INSERT INTO provider_activation_events (provider_id, event_type, actor, details_json) VALUES (?, ?, ?, ?)').bind(providerId, passed ? 'REVIEW_GATE_PASSED' : 'REVIEW_GATE_FAILED', reviewer, JSON.stringify({ gate, evidenceUrl, evidenceHash, notes })).run(); return next; }
export async function activateProvider(env: Env, providerId: string, approver: string, notes: string[] = []): Promise<ProviderReviewRecord> { const rows = await env.DB.prepare('SELECT * FROM provider_reviews WHERE provider_id = ?').bind(providerId).all<Record<string, unknown>>(); if (!rows.results[0]) throw new Error('Provider has no D1 review record'); const current = rowToReview(rows.results[0]); if (!current.termsReviewed || !current.schemaValidated || !current.authorityValidated || !current.securityReviewed) throw new Error('All provider review gates must pass before activation'); const now = new Date().toISOString(); await env.DB.batch([env.DB.prepare('UPDATE provider_reviews SET lifecycle = ?, approved_by = ?, approved_at = ?, notes_json = ?, updated_at = CURRENT_TIMESTAMP WHERE provider_id = ?').bind('ACTIVE', approver, now, JSON.stringify([...(current.notes ?? []), ...notes]), providerId), env.DB.prepare('INSERT INTO provider_activation_events (provider_id, event_type, actor, details_json) VALUES (?, ?, ?, ?)').bind(providerId, 'ACTIVATED', approver, JSON.stringify({ notes }))]); return { ...current, lifecycle: 'ACTIVE', approvedBy: approver, approvedAt: now, updatedAt: now, notes: [...(current.notes ?? []), ...notes] }; }
export async function deactivateProvider(env: Env, providerId: string, actor: string, notes: string[] = []): Promise<void> { await env.DB.prepare('UPDATE provider_reviews SET lifecycle = ?, approved_by = NULL, approved_at = NULL, updated_at = CURRENT_TIMESTAMP WHERE provider_id = ?').bind('DISCOVERED', providerId).run(); await env.DB.prepare('INSERT INTO provider_activation_events (provider_id, event_type, actor, details_json) VALUES (?, ?, ?, ?)').bind(providerId, 'DEACTIVATED', actor, JSON.stringify({ notes })).run(); }
