import type { Env } from '../types';
import { createRegistry } from '../registry';
import { loadProviderReviews } from '../repositories/provider-reviews';
import { providerIsRoutable } from './provider-review';

type CountRow = { count: number };
const count = async (env: Env, sql: string): Promise<number> => { const result = await env.DB.prepare(sql).first<CountRow>(); return Number(result?.count ?? 0); };

export async function dashboardSummary(env: Env) { const reviews = await loadProviderReviews(env); const registry = createRegistry(env, reviews); const providers = [...registry.values()]; return { environment: env.ENVIRONMENT ?? 'unknown', mockMode: env.ENVIRONMENT === 'local' && env.MOCK_PROVIDER_MODE === 'true', generatedAt: new Date().toISOString(), providers: { total: providers.length, active: providers.filter(providerIsRoutable).length, inactive: providers.filter((provider) => !providerIsRoutable(provider)).length, reviewReady: providers.filter((provider) => provider.review.lifecycle === 'APPROVED').length }, corpus: { indexedCases: await count(env, 'SELECT COUNT(*) AS count FROM cases'), ingestionEvents: await count(env, 'SELECT COUNT(*) AS count FROM ingestion_events'), citationEdges: await count(env, 'SELECT COUNT(*) AS count FROM citation_edges') }, audit: { events: await count(env, 'SELECT COUNT(*) AS count FROM audit_logs'), activationEvents: await count(env, 'SELECT COUNT(*) AS count FROM provider_activation_events') } }; }
export async function dashboardProviders(env: Env) { const reviews = await loadProviderReviews(env); const registry = createRegistry(env, reviews); return { generatedAt: new Date().toISOString(), providers: [...registry.values()].map((provider) => ({ id: provider.id, endpoint: provider.endpoint, jurisdiction: provider.jurisdiction, coverageCount: provider.coverage.length, coverage: provider.coverage, capabilities: provider.capabilities, review: provider.review, routable: providerIsRoutable(provider) })) }; }
export async function dashboardActivity(env: Env) { const [ingestion, activations] = await Promise.all([env.DB.prepare('SELECT id, request_id, provider, kind, created_at FROM ingestion_events ORDER BY id DESC LIMIT 25').all<Record<string, unknown>>(), env.DB.prepare('SELECT id, provider_id, event_type, actor, created_at FROM provider_activation_events ORDER BY id DESC LIMIT 25').all<Record<string, unknown>>()]); return { generatedAt: new Date().toISOString(), ingestion: ingestion.results, activations: activations.results }; }
