import type { D1Database } from '@cloudflare/workers-types';
import type { JudgeObservation, JudgePrediction } from '../types';
import type { JudgeObservationInput } from '../schemas';
import type { JudgeSource, JudgeProfileIdentity, AdversarialReview, JudgeCaseObservation, Matter, ProceduralEvent, DiscoveryObject, FilingArtifact, FilingGate, AuthorityRecord, AuthorityEdge } from '../types';
const sourceWeight: Record<JudgeObservation['sourceClass'], number> = { 'official-procedure': 1, 'published-order': .95, 'published-opinion': .9, docket: .8, 'user-record': .75, secondary: .45 };
function issueTerms(issue: string): string[] { return issue.toLowerCase().split(/[^a-z0-9]+/).filter((term) => term.length > 2); }
function matchesIssue(text: string, terms: string[]): boolean { return terms.length > 0 && terms.some((term) => text.toLowerCase().includes(term)); }
async function assertMatterScope(db: D1Database, tenantId: string, matterId: string | undefined, judgeId?: string): Promise<void> { if (!matterId) return; const row = await db.prepare('SELECT payload_json FROM matters WHERE tenant_id = ? AND matter_id = ?').bind(tenantId, matterId).first<{ payload_json: string }>(); if (!row) throw new Error('matter_not_found_or_out_of_scope'); const matter = JSON.parse(row.payload_json) as { judgeId?: string }; if (judgeId && !matter.judgeId) throw new Error('matter_judge_required'); if (judgeId && matter.judgeId !== judgeId) throw new Error('matter_judge_mismatch'); }
async function assertSourceScope(db: D1Database, tenantId: string, sourceId: string | undefined, judgeId?: string): Promise<void> { if (!sourceId) return; const query = judgeId ? db.prepare('SELECT id FROM judge_sources WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(sourceId, tenantId, judgeId) : db.prepare('SELECT id FROM judge_sources WHERE id = ? AND tenant_id = ?').bind(sourceId, tenantId); if (!await query.first<{ id: string }>()) throw new Error('source_not_found_or_out_of_scope'); }
async function assertSourceVerified(db: D1Database, tenantId: string, sourceId: string | undefined, judgeId: string): Promise<void> { if (!sourceId) return; const row = await db.prepare('SELECT verification_status FROM judge_sources WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(sourceId, tenantId, judgeId).first<{ verification_status: string }>(); if (!row) throw new Error('source_not_found_or_out_of_scope'); if (row.verification_status !== 'VERIFIED') throw new Error('source_verification_required'); }
export async function assertFilingEvidence(db: D1Database, tenantId: string, matterId: string, evidenceIds: string[]): Promise<void> {
  const matterRow = await db.prepare('SELECT payload_json FROM matters WHERE tenant_id = ? AND matter_id = ?').bind(tenantId, matterId).first<{ payload_json: string }>();
  const matter = matterRow ? JSON.parse(matterRow.payload_json) as { judgeId?: string } : null;
  if (!matter) throw new Error('matter_not_found_or_out_of_scope');
  if (!matter.judgeId) throw new Error('filing_matter_judge_required');
  for (const reference of evidenceIds) {
    const separator = reference.indexOf(':');
    if (separator < 1 || separator === reference.length - 1) throw new Error('filing_evidence_reference_invalid');
    const kind = reference.slice(0, separator);
    const id = reference.slice(separator + 1);
    let found: { id: string; verification_status?: string; status?: string; human_review?: string; source_id?: string | null } | null = null;
    if (kind === 'source') found = await db.prepare('SELECT id, verification_status FROM judge_sources WHERE id = ? AND tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?)').bind(id, tenantId, matter.judgeId, matterId).first<{ id: string; verification_status: string }>();
    else if (kind === 'event') found = await db.prepare('SELECT id, status, source_id FROM procedural_events WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(id, tenantId, matterId).first<{ id: string; status: string; source_id: string | null }>();
    else if (kind === 'discovery') found = await db.prepare('SELECT id, status, source_id FROM discovery_objects WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(id, tenantId, matterId).first<{ id: string; status: string; source_id: string | null }>();
    else if (kind === 'authority') found = await db.prepare('SELECT id, status, source_id FROM authority_records WHERE id = ? AND tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?)').bind(id, tenantId, matter.judgeId, matterId).first<{ id: string; status: string; source_id: string | null }>();
    else if (kind === 'adversarial') found = await db.prepare('SELECT id, status FROM judge_adversarial_runs WHERE id = ? AND tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?)').bind(id, tenantId, matter.judgeId, matterId).first<{ id: string; status: string }>();
    else if (kind === 'prediction') found = await db.prepare('SELECT id, human_review FROM judge_predictions WHERE id = ? AND tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?)').bind(id, tenantId, matter.judgeId, matterId).first<{ id: string; human_review: string }>();
    else throw new Error('filing_evidence_kind_invalid');
    if (!found) throw new Error('filing_evidence_not_found_or_out_of_scope');
    const verified = kind === 'source' ? found.verification_status === 'VERIFIED' : kind === 'adversarial' ? found.status === 'APPROVED' : kind === 'prediction' ? found.human_review === 'APPROVED' : found.status === 'VERIFIED';
    if (!verified) throw new Error('filing_evidence_not_verified');
    if (kind !== 'source' && found.source_id) await assertSourceVerified(db, tenantId, found.source_id, matter.judgeId);
  }
}
export function buildJudgePrediction(judgeId: string, issue: string, observations: JudgeObservation[], matterId?: string, caseObservations: JudgeCaseObservation[] = []): JudgePrediction {
  const terms = issueTerms(issue);
  const scoped = observations.filter((o) => o.judgeId === judgeId && (!matterId || !o.matterId || o.matterId === matterId));
  const relevantObservations = scoped.filter((o) => matchesIssue(`${o.dimension} ${o.proposition} ${o.value}`, terms));
  const usable = relevantObservations.filter((o) => o.status === 'VERIFIED');
  const relevantCases = caseObservations.filter((o) => o.judgeId === judgeId && (!matterId || !o.matterId || o.matterId === matterId) && matchesIssue(`${o.proceduralPosture} ${o.issueClass} ${o.motionType ?? ''} ${o.ruling}`, terms));
  const comparable = relevantCases.filter((o) => o.status === 'VERIFIED');
  const scores = new Map<string, number>();
  for (const o of usable) scores.set(o.value, (scores.get(o.value) ?? 0) + o.confidence * sourceWeight[o.sourceClass]);
  for (const o of comparable) scores.set(o.ruling, (scores.get(o.ruling) ?? 0) + o.comparabilityScore);
  const total = [...scores.values()].reduce((a, b) => a + b, 0) || 1;
  const outcomes = [...scores.entries()].map(([outcome, score]) => ({ outcome, score: Number((score / total).toFixed(4)) })).sort((a, b) => b.score - a.score);
  const reasons = [...usable.slice(0, 6).map((o) => `${o.dimension}: ${o.proposition} → ${o.value} (${o.status}, ${o.sourceClass})`), ...comparable.slice(0, 6).map((o) => `Comparable case ${o.caseId}: ${o.proceduralPosture}; ${o.issueClass} → ${o.ruling} (comparability ${o.comparabilityScore})`)];
  const disputedRelevant = relevantObservations.some((o) => o.status === 'DISPUTED') || relevantCases.some((o) => o.status === 'DISPUTED');
  const unverifiedRelevant = relevantObservations.some((o) => o.status === 'UNVERIFIED') || relevantCases.some((o) => o.status === 'UNVERIFIED');
  const evidenceWasExcluded = disputedRelevant || unverifiedRelevant;
  const uncertaintyReasons = outcomes.length === 0 ? ['No verified issue-relevant observations or comparable case rulings were found.'] : evidenceWasExcluded ? ['Relevant unverified or disputed records were excluded from scoring.'] : usable.length + comparable.length < 3 ? ['Fewer than three verified issue-relevant records.'] : [];
  return { judgeId, matterId, issue, status: outcomes.length ? 'PREDICTION_AVAILABLE' : 'RECORD_TOO_INCOMPLETE', outcomes, rationale: reasons, sourceObservationIds: [...usable.map((o) => o.id), ...comparable.map((o) => `case:${o.id}`)], uncertainty: { level: outcomes.length === 0 || usable.length + comparable.length < 3 || evidenceWasExcluded ? 'HIGH' : usable.length + comparable.length < 8 ? 'MEDIUM' : 'LOW', reasons: uncertaintyReasons }, limitation: 'MODEL-BASED — NOT A GUARANTEE', model: 'evidence-weighted-heuristic-v1', humanReview: 'REQUIRED', createdAt: new Date().toISOString() };
}
export async function listJudgeObservations(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<JudgeObservation[]> { const query = matterId ? db.prepare('SELECT payload_json FROM judge_observations WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY observed_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT payload_json FROM judge_observations WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY observed_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as JudgeObservation); }
export async function listJudgeSources(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<JudgeSource[]> { const query = matterId ? db.prepare('SELECT payload_json FROM judge_sources WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY retrieved_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT payload_json FROM judge_sources WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY retrieved_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as JudgeSource); }
export async function listJudgePredictions(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<Array<Record<string, unknown>>> { const query = matterId ? db.prepare('SELECT id, payload_json FROM judge_predictions WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY created_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT id, payload_json FROM judge_predictions WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY created_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ id: string; payload_json: string }>(); return rows.results.map((row) => ({ id: row.id, ...JSON.parse(row.payload_json) as Record<string, unknown> })); }
export async function listJudgeAdversarialRuns(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<Array<Record<string, unknown>>> { const query = matterId ? db.prepare('SELECT id, payload_json FROM judge_adversarial_runs WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY created_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT id, payload_json FROM judge_adversarial_runs WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY created_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ id: string; payload_json: string }>(); return rows.results.map((row) => ({ id: row.id, ...JSON.parse(row.payload_json) as Record<string, unknown> })); }
export async function listJudgeEngineReports(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<Array<Record<string, unknown>>> { const query = matterId ? db.prepare('SELECT id, payload_json FROM judge_engine_reports WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY created_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT id, payload_json FROM judge_engine_reports WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY created_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ id: string; payload_json: string }>(); return rows.results.map((row) => ({ id: row.id, ...JSON.parse(row.payload_json) as Record<string, unknown> })); }
export async function addJudgeObservation(db: D1Database, input: JudgeObservationInput & { tenantId: string }): Promise<JudgeObservation> { const recordedAt = new Date().toISOString(); await assertSourceScope(db, input.tenantId, input.sourceId, input.judgeId); await assertMatterScope(db, input.tenantId, input.matterId, input.judgeId); const observation: JudgeObservation = { ...input, id: crypto.randomUUID(), status: 'UNVERIFIED', observedAt: `${input.observedAt}T00:00:00.000Z`, recordedAt }; const statements = [db.prepare('INSERT INTO judge_observations (id, tenant_id, judge_id, matter_id, source_id, dimension, status, observed_at, recorded_at, verification_note, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(observation.id, observation.tenantId, observation.judgeId, observation.matterId ?? null, observation.sourceId ?? null, observation.dimension, observation.status, observation.observedAt, observation.recordedAt, null, JSON.stringify(observation))]; await db.batch(statements); return observation; }
export async function reviewJudgeObservation(db: D1Database, tenantId: string, judgeId: string, input: { observationId: string; reviewer: string; decision: 'VERIFIED' | 'DISPUTED'; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (input.decision === 'VERIFIED' && !input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const row = await db.prepare('SELECT payload_json FROM judge_observations WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.observationId, tenantId, judgeId).first<{ payload_json: string }>(); if (!row) throw new Error('observation_not_found_or_out_of_scope'); const observation = JSON.parse(row.payload_json) as JudgeObservation; if (input.decision === 'VERIFIED') await assertSourceVerified(db, tenantId, observation.sourceId, judgeId); observation.status = input.decision; observation.verificationNote = input.notes; await db.batch([db.prepare('UPDATE judge_observations SET status = ?, verification_note = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.decision, input.notes, JSON.stringify(observation), input.observationId, tenantId, judgeId), db.prepare('INSERT INTO judge_profile_reviews (tenant_id, judge_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(tenantId, observation.judgeId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function profileAndPredict(db: D1Database, tenantId: string, judgeId: string, issue: string, matterId?: string): Promise<JudgePrediction> { await assertMatterScope(db, tenantId, matterId, judgeId); return buildJudgePrediction(judgeId, issue, await listJudgeObservations(db, tenantId, judgeId), matterId, await listJudgeCaseObservations(db, tenantId, judgeId)); }
export async function addJudgeSource(db: D1Database, bucket: R2Bucket, input: { tenantId: string; judgeId: string; matterId?: string; sourceClass: JudgeSource['sourceClass']; sourceUrl?: string; title?: string; effectiveDate?: string; content?: string }): Promise<JudgeSource> { await assertMatterScope(db, input.tenantId, input.matterId, input.judgeId); const retrievedAt = new Date().toISOString(); const sourceHash = input.content ? Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(input.content)))).map((b) => b.toString(16).padStart(2, '0')).join('') : undefined; const id = crypto.randomUUID(); const r2Key = input.content ? `judge-sources/${input.tenantId}/${input.judgeId}/${id}.txt` : undefined; if (input.content && r2Key) await bucket.put(r2Key, input.content, { httpMetadata: { contentType: 'text/plain' }, customMetadata: { sourceHash: sourceHash!, judgeId: input.judgeId, tenantId: input.tenantId } }); const source: JudgeSource = { id, tenantId: input.tenantId, judgeId: input.judgeId, matterId: input.matterId, sourceClass: input.sourceClass, sourceUrl: input.sourceUrl, sourceHash, r2Key, title: input.title, effectiveDate: input.effectiveDate, retrievedAt, verificationStatus: 'UNVERIFIED' }; await db.prepare('INSERT INTO judge_sources (id, tenant_id, judge_id, matter_id, source_class, source_url, source_hash, r2_key, title, effective_date, retrieved_at, verification_status, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(id, source.tenantId, source.judgeId, source.matterId ?? null, source.sourceClass, source.sourceUrl ?? null, source.sourceHash ?? null, source.r2Key ?? null, source.title ?? null, source.effectiveDate ?? null, source.retrievedAt, source.verificationStatus, JSON.stringify(source)).run(); return source; }
export async function addJudgeSourceBytes(db: D1Database, bucket: R2Bucket, input: { tenantId: string; judgeId: string; sourceClass: JudgeSource['sourceClass']; sourceUrl?: string; title?: string; effectiveDate?: string; bytes: ArrayBuffer; contentType: string }): Promise<JudgeSource> { const retrievedAt = new Date().toISOString(); const sourceHash = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', input.bytes))).map((b) => b.toString(16).padStart(2, '0')).join(''); const id = crypto.randomUUID(); const extension = input.contentType.includes('pdf') ? 'pdf' : input.contentType.includes('html') ? 'html' : 'bin'; const r2Key = `judge-sources/${input.tenantId}/${input.judgeId}/${id}.${extension}`; await bucket.put(r2Key, input.bytes, { httpMetadata: { contentType: input.contentType }, customMetadata: { sourceHash, judgeId: input.judgeId, tenantId: input.tenantId } }); const source: JudgeSource = { id, tenantId: input.tenantId, judgeId: input.judgeId, sourceClass: input.sourceClass, sourceUrl: input.sourceUrl, sourceHash, r2Key, title: input.title, effectiveDate: input.effectiveDate, retrievedAt, verificationStatus: 'UNVERIFIED' }; await db.prepare('INSERT INTO judge_sources (id, tenant_id, judge_id, source_class, source_url, source_hash, r2_key, title, effective_date, retrieved_at, verification_status, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(id, source.tenantId, source.judgeId, source.sourceClass, source.sourceUrl ?? null, source.sourceHash, source.r2Key, source.title ?? null, source.effectiveDate ?? null, source.retrievedAt, source.verificationStatus, JSON.stringify(source)).run(); return source; }
export async function ingestOfficialJudgeSource(db: D1Database, bucket: R2Bucket, input: { tenantId: string; judgeId: string; url: string; sourceClass: 'official-procedure' | 'published-order' | 'published-opinion'; title?: string; effectiveDate?: string }): Promise<JudgeSource> { const requested = new URL(input.url); const allowed = ['ninthcircuit.org', 'supremecourt.flcourts.gov', 'flcourts.gov', 'floridabar.org']; if (!allowed.some((host) => requested.hostname === host || requested.hostname.endsWith(`.${host}`))) throw new Error('official_source_domain_not_allowed'); const response = await fetch(requested, { headers: { Accept: 'text/html,application/pdf,text/plain' }, redirect: 'follow' }); const finalUrl = new URL(response.url); if (!allowed.some((host) => finalUrl.hostname === host || finalUrl.hostname.endsWith(`.${host}`))) throw new Error('official_source_redirect_not_allowed'); if (!response.ok) throw new Error(`official_source_fetch_${response.status}`); const contentType = (response.headers.get('content-type') ?? 'application/octet-stream').split(';')[0]!.trim().toLowerCase(); if (!['application/pdf', 'text/html', 'text/plain', 'application/xhtml+xml'].includes(contentType)) throw new Error('official_source_content_type_not_allowed'); const bytes = await response.arrayBuffer(); if (bytes.byteLength > 2_000_000) throw new Error('official_source_too_large'); return addJudgeSourceBytes(db, bucket, { tenantId: input.tenantId, judgeId: input.judgeId, sourceClass: input.sourceClass, sourceUrl: finalUrl.toString(), title: input.title, effectiveDate: input.effectiveDate, bytes, contentType }); }
export async function reviewJudgeSource(db: D1Database, tenantId: string, judgeId: string, input: { sourceId: string; reviewer: string; decision: 'VERIFIED' | 'REJECTED'; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (input.decision === 'VERIFIED' && !input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const row = await db.prepare('SELECT payload_json FROM judge_sources WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.sourceId, tenantId, judgeId).first<{ payload_json: string }>(); if (!row) throw new Error('source_not_found_or_out_of_scope'); const source = JSON.parse(row.payload_json) as JudgeSource; source.verificationStatus = input.decision; await db.batch([db.prepare('UPDATE judge_sources SET verification_status = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(source.verificationStatus, JSON.stringify(source), input.sourceId, tenantId, judgeId), db.prepare('INSERT INTO judge_source_reviews (tenant_id, source_id, judge_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(tenantId, input.sourceId, judgeId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function reviewJudgePrediction(db: D1Database, tenantId: string, judgeId: string, input: { predictionId: string; reviewer: string; decision: 'APPROVED' | 'REJECTED'; notes: string }): Promise<void> { const row = await db.prepare('SELECT payload_json FROM judge_predictions WHERE id = ? AND judge_id = ? AND tenant_id = ?').bind(input.predictionId, judgeId, tenantId).first<{ payload_json: string }>(); if (!row) throw new Error('prediction_not_found'); const payload = JSON.parse(row.payload_json) as Record<string, unknown>; if (payload.humanReview !== 'REQUIRED') throw new Error('prediction_review_already_decided'); payload.humanReview = input.decision; await db.batch([db.prepare('UPDATE judge_predictions SET human_review = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND judge_id = ? AND human_review = ?').bind(input.decision, JSON.stringify(payload), input.predictionId, tenantId, judgeId, 'REQUIRED'), db.prepare('INSERT INTO judge_profile_reviews (tenant_id, judge_id, prediction_id, reviewer, decision, notes) VALUES (?, ?, ?, ?, ?, ?)').bind(tenantId, judgeId, input.predictionId, input.reviewer, input.decision, input.notes)]); }
export async function saveJudgeIdentity(db: D1Database, identity: JudgeProfileIdentity): Promise<void> { await db.prepare('INSERT INTO judge_profiles (tenant_id, judge_id, payload_json, last_verified, status) VALUES (?, ?, ?, ?, ?) ON CONFLICT(tenant_id, judge_id) DO UPDATE SET payload_json = excluded.payload_json, last_verified = excluded.last_verified, status = excluded.status').bind(identity.tenantId, identity.judgeId, JSON.stringify(identity), identity.lastVerified, identity.status).run(); }
export async function getJudgeIdentity(db: D1Database, tenantId: string, judgeId: string): Promise<JudgeProfileIdentity | null> { const row = await db.prepare('SELECT payload_json FROM judge_profiles WHERE tenant_id = ? AND judge_id = ?').bind(tenantId, judgeId).first<{ payload_json: string }>(); return row ? JSON.parse(row.payload_json) as JudgeProfileIdentity : null; }
export async function listJudgeIdentities(db: D1Database, tenantId: string, filters: { court?: string; county?: string; judicialCircuit?: string; division?: string; limit?: number; offset?: number } = {}): Promise<JudgeProfileIdentity[]> { const rows = await db.prepare('SELECT payload_json FROM judge_profiles WHERE tenant_id = ? ORDER BY judge_id ASC').bind(tenantId).all<{ payload_json: string }>(); const matches = rows.results.map((row) => JSON.parse(row.payload_json) as JudgeProfileIdentity).filter((identity) => (!filters.court || identity.court?.toLowerCase().includes(filters.court.toLowerCase())) && (!filters.county || identity.county?.toLowerCase().includes(filters.county.toLowerCase())) && (!filters.judicialCircuit || identity.judicialCircuit?.toLowerCase().includes(filters.judicialCircuit.toLowerCase())) && (!filters.division || identity.division?.toLowerCase().includes(filters.division.toLowerCase()))); const offset = Math.max(0, filters.offset ?? 0); const limit = Math.min(100, Math.max(1, filters.limit ?? 100)); return matches.slice(offset, offset + limit); }
export async function listJudgeCaseObservations(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<JudgeCaseObservation[]> { const query = matterId ? db.prepare('SELECT payload_json FROM judge_case_observations WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY created_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT payload_json FROM judge_case_observations WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY created_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as JudgeCaseObservation); }
export async function addJudgeCaseObservation(db: D1Database, input: Omit<JudgeCaseObservation, 'id' | 'status' | 'createdAt'> & { tenantId: string }): Promise<JudgeCaseObservation> { await assertSourceScope(db, input.tenantId, input.sourceId, input.judgeId); await assertMatterScope(db, input.tenantId, input.matterId, input.judgeId); const observation: JudgeCaseObservation = { ...input, id: crypto.randomUUID(), status: 'UNVERIFIED', createdAt: new Date().toISOString() }; await db.prepare('INSERT INTO judge_case_observations (id, tenant_id, judge_id, matter_id, case_id, court, division, case_type, procedural_posture, issue_class, motion_type, requested_relief, ruling, reasons, comparability_score, source_id, status, created_at, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(observation.id, observation.tenantId, observation.judgeId, observation.matterId ?? null, observation.caseId, observation.court, observation.division ?? null, observation.caseType ?? null, observation.proceduralPosture, observation.issueClass, observation.motionType ?? null, observation.requestedRelief ?? null, observation.ruling, observation.reasons ?? null, observation.comparabilityScore, observation.sourceId ?? null, observation.status, observation.createdAt, JSON.stringify(observation)).run(); return observation; }
export async function reviewJudgeCaseObservation(db: D1Database, tenantId: string, judgeId: string, input: { observationId: string; reviewer: string; decision: 'VERIFIED' | 'DISPUTED'; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (input.decision === 'VERIFIED' && !input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const row = await db.prepare('SELECT payload_json FROM judge_case_observations WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.observationId, tenantId, judgeId).first<{ payload_json: string }>(); if (!row) throw new Error('case_observation_not_found_or_out_of_scope'); const observation = JSON.parse(row.payload_json) as JudgeCaseObservation; if (input.decision === 'VERIFIED') await assertSourceVerified(db, tenantId, observation.sourceId, judgeId); observation.status = input.decision; await db.batch([db.prepare('UPDATE judge_case_observations SET status = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.decision, JSON.stringify(observation), input.observationId, tenantId, judgeId), db.prepare('INSERT INTO judge_case_reviews (tenant_id, observation_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(tenantId, input.observationId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export function buildAdversarialReview(tenantId: string, judgeId: string, issue: string, observations: JudgeObservation[], matterId?: string, caseObservations: JudgeCaseObservation[] = []): AdversarialReview {
  const terms = issueTerms(issue);
  const scopedObservations = observations.filter((o) => o.judgeId === judgeId && (!matterId || !o.matterId || o.matterId === matterId) && matchesIssue(`${o.dimension} ${o.proposition} ${o.value}`, terms));
  const scopedCases = caseObservations.filter((o) => o.judgeId === judgeId && (!matterId || !o.matterId || o.matterId === matterId) && matchesIssue(`${o.proceduralPosture} ${o.issueClass} ${o.motionType ?? ''} ${o.ruling}`, terms));
  const verifiedCases = scopedCases.filter((o) => o.status === 'VERIFIED');
  const unverifiedCaseCount = scopedCases.length - verifiedCases.length;
  const evidenceCount = scopedObservations.filter((o) => o.status === 'VERIFIED').length + verifiedCases.length;
  const unverifiedCount = scopedObservations.filter((o) => o.status !== 'VERIFIED').length + unverifiedCaseCount;
  const red = [evidenceCount < 3 ? 'Small issue-relevant comparable-evidence set; a general trend is unsupported.' : 'Comparable-evidence count is not independently validated.', unverifiedCount > 0 ? `${unverifiedCount} issue-relevant evidence record(s) remain unverified or disputed and must not support a conclusion.` : 'No unverified issue-relevant evidence was used in the analysis.', verifiedCases.length > 0 ? `Case-based analysis includes ${verifiedCases.length} verified comparable case observation(s); confirm comparability to the present issue.` : 'No verified issue-relevant comparable case observations are available.'];
  const blue = [evidenceCount < 3 ? 'Use the profile only as a limited lead and obtain additional comparable records.' : 'Limit the conclusion to the documented issue and procedural posture.', 'Separate procedural evidence from merits outcomes and disclose source limitations.', verifiedCases.length > 0 ? 'Check each comparable case for posture, issue, requested relief, and ruling before relying on it.' : 'Do not imply a case-based trend without verified comparable cases.'];
  const purple: AdversarialReview['purple'] = [{ position: 'Use the judge profile to guide issue framing', classification: evidenceCount >= 3 && unverifiedCount === 0 ? 'DEFENSIBLE' : 'WEAK' }, { position: 'Use verified comparable cases as limited analogies', classification: verifiedCases.length > 0 ? 'DEFENSIBLE' : 'WEAK' }, { position: 'Predict a guaranteed ruling', classification: 'WEAK' }];
  return { id: crypto.randomUUID(), tenantId, matterId, judgeId, issue, status: 'HUMAN_REVIEW_REQUIRED', red, blue, purple, createdAt: new Date().toISOString() };
}
export async function reviewAdversarialRun(db: D1Database, tenantId: string, judgeId: string, input: { reviewId: string; reviewer: string; decision: 'APPROVED' | 'REJECTED'; notes: string }): Promise<void> { const row = await db.prepare('SELECT payload_json FROM judge_adversarial_runs WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.reviewId, tenantId, judgeId).first<{ payload_json: string }>(); if (!row) throw new Error('adversarial_review_not_found_or_out_of_scope'); const review = JSON.parse(row.payload_json) as AdversarialReview; if (review.status !== 'HUMAN_REVIEW_REQUIRED') throw new Error('adversarial_review_already_decided'); review.status = input.decision; await db.batch([db.prepare('UPDATE judge_adversarial_runs SET status = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(review.status, JSON.stringify(review), input.reviewId, tenantId, judgeId), db.prepare('INSERT INTO judge_adversarial_reviews (tenant_id, review_id, judge_id, reviewer, decision, notes) VALUES (?, ?, ?, ?, ?, ?)').bind(tenantId, input.reviewId, judgeId, input.reviewer, input.decision, input.notes)]); }
export async function coordinateProfileEvent(ns: { idFromName(name: string): unknown; get(id: unknown): { fetch(input: string, init?: RequestInit): Promise<Response> } } | undefined, tenantId: string, judgeId: string, event: unknown): Promise<void> { if (!ns) return; await ns.get(ns.idFromName(`judge:${tenantId}:${judgeId}`)).fetch('https://judge-coordinator/event', { method: 'POST', body: JSON.stringify({ tenantId, judgeId, event }), headers: { 'content-type': 'application/json' } }); }
export async function saveMatter(db: D1Database, matter: Matter): Promise<void> { const existing = await db.prepare('SELECT payload_json FROM matters WHERE tenant_id = ? AND matter_id = ?').bind(matter.tenantId, matter.matterId).first<{ payload_json: string }>(); if (existing) { const prior = JSON.parse(existing.payload_json) as Matter; if (prior.judgeId !== matter.judgeId && (prior.judgeId || matter.judgeId)) throw new Error('matter_judge_reassignment_blocked'); } await db.prepare('INSERT INTO matters (tenant_id, matter_id, payload_json, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(tenant_id, matter_id) DO UPDATE SET payload_json = excluded.payload_json, status = excluded.status, updated_at = excluded.updated_at').bind(matter.tenantId, matter.matterId, JSON.stringify(matter), matter.status, matter.createdAt, matter.updatedAt).run(); }
export async function getMatter(db: D1Database, tenantId: string, matterId: string): Promise<Matter | null> { const row = await db.prepare('SELECT payload_json FROM matters WHERE tenant_id = ? AND matter_id = ?').bind(tenantId, matterId).first<{ payload_json: string }>(); return row ? JSON.parse(row.payload_json) as Matter : null; }
export async function addProceduralEvent(db: D1Database, input: Omit<ProceduralEvent, 'id' | 'createdAt'>): Promise<ProceduralEvent> { const matter = await getMatter(db, input.tenantId, input.matterId); if (!matter) throw new Error('matter_not_found'); await assertSourceScope(db, input.tenantId, input.sourceId, matter.judgeId); const event: ProceduralEvent = { ...input, status: 'UNVERIFIED', id: crypto.randomUUID(), createdAt: new Date().toISOString() }; await db.prepare('INSERT INTO procedural_events (id, tenant_id, matter_id, event_type, event_date, source_id, status, payload_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(event.id, event.tenantId, event.matterId, event.eventType, event.eventDate, event.sourceId ?? null, event.status, JSON.stringify(event.payload), event.createdAt).run(); return event; }
export async function reviewProceduralEvent(db: D1Database, tenantId: string, matterId: string, eventId: string, input: { reviewer: string; decision: 'VERIFIED' | 'DISPUTED'; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (input.decision === 'VERIFIED' && !input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const matter = await getMatter(db, tenantId, matterId); if (!matter) throw new Error('matter_not_found_or_out_of_scope'); const row = await db.prepare('SELECT source_id FROM procedural_events WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(eventId, tenantId, matterId).first<{ source_id: string | null }>(); if (!row) throw new Error('procedural_event_not_found_or_out_of_scope'); if (input.decision === 'VERIFIED') await assertSourceVerified(db, tenantId, row.source_id ?? undefined, matter.judgeId ?? ''); await db.batch([db.prepare('UPDATE procedural_events SET status = ? WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(input.decision, eventId, tenantId, matterId), db.prepare('INSERT INTO procedural_event_reviews (tenant_id, matter_id, event_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(tenantId, matterId, eventId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function listProceduralEventReviews(db: D1Database, tenantId: string, matterId: string, eventId: string): Promise<Array<Record<string, unknown>>> { const rows = await db.prepare('SELECT id, event_id, reviewer, decision, notes, verification_source_url, verification_source_hash, created_at FROM procedural_event_reviews WHERE tenant_id = ? AND matter_id = ? AND event_id = ? ORDER BY id ASC').bind(tenantId, matterId, eventId).all<Record<string, unknown>>(); return rows.results; }
export async function listProceduralEvents(db: D1Database, tenantId: string, matterId: string): Promise<ProceduralEvent[]> { const rows = await db.prepare('SELECT id, tenant_id, matter_id, event_type, event_date, source_id, status, payload_json, created_at FROM procedural_events WHERE tenant_id = ? AND matter_id = ? ORDER BY event_date ASC, created_at ASC').bind(tenantId, matterId).all<Record<string, unknown>>(); return rows.results.map((row) => ({ id: String(row.id), tenantId: String(row.tenant_id), matterId: String(row.matter_id), eventType: String(row.event_type), eventDate: String(row.event_date), sourceId: row.source_id ? String(row.source_id) : undefined, status: row.status as ProceduralEvent['status'], payload: JSON.parse(String(row.payload_json)) as Record<string, unknown>, createdAt: String(row.created_at) })); }
export async function addDiscoveryObject(db: D1Database, input: Omit<DiscoveryObject, 'id' | 'createdAt'>): Promise<DiscoveryObject> { const matter = await getMatter(db, input.tenantId, input.matterId); if (!matter) throw new Error('matter_not_found'); await assertSourceScope(db, input.tenantId, input.sourceId, matter.judgeId); const object: DiscoveryObject = { ...input, status: 'UNVERIFIED', id: crypto.randomUUID(), createdAt: new Date().toISOString() }; await db.prepare('INSERT INTO discovery_objects (id, tenant_id, matter_id, kind, request_number, production_status, status, source_id, payload_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(object.id, object.tenantId, object.matterId, object.kind, object.requestNumber ?? null, object.productionStatus, object.status, object.sourceId ?? null, JSON.stringify(object), object.createdAt).run(); return object; }
export async function reviewDiscoveryObject(db: D1Database, tenantId: string, matterId: string, discoveryId: string, input: { reviewer: string; decision: 'VERIFIED' | 'DISPUTED'; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (input.decision === 'VERIFIED' && !input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const matter = await getMatter(db, tenantId, matterId); if (!matter) throw new Error('matter_not_found_or_out_of_scope'); const row = await db.prepare('SELECT payload_json FROM discovery_objects WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(discoveryId, tenantId, matterId).first<{ payload_json: string }>(); if (!row) throw new Error('discovery_object_not_found_or_out_of_scope'); const object = JSON.parse(row.payload_json) as DiscoveryObject; if (input.decision === 'VERIFIED') await assertSourceVerified(db, tenantId, object.sourceId, matter.judgeId ?? ''); object.status = input.decision; await db.batch([db.prepare('UPDATE discovery_objects SET status = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(input.decision, JSON.stringify(object), discoveryId, tenantId, matterId), db.prepare('INSERT INTO discovery_object_reviews (tenant_id, matter_id, discovery_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(tenantId, matterId, discoveryId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function listDiscoveryObjectReviews(db: D1Database, tenantId: string, matterId: string, discoveryId: string): Promise<Array<Record<string, unknown>>> { const rows = await db.prepare('SELECT id, discovery_id, reviewer, decision, notes, verification_source_url, verification_source_hash, created_at FROM discovery_object_reviews WHERE tenant_id = ? AND matter_id = ? AND discovery_id = ? ORDER BY id ASC').bind(tenantId, matterId, discoveryId).all<Record<string, unknown>>(); return rows.results; }
export async function listDiscoveryObjects(db: D1Database, tenantId: string, matterId: string): Promise<DiscoveryObject[]> { const rows = await db.prepare('SELECT payload_json FROM discovery_objects WHERE tenant_id = ? AND matter_id = ? ORDER BY created_at ASC').bind(tenantId, matterId).all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as DiscoveryObject); }
export async function createFilingArtifact(db: D1Database, bucket: R2Bucket, input: { tenantId: string; matterId: string; kind: string; content?: string }): Promise<FilingArtifact> { if (!await getMatter(db, input.tenantId, input.matterId)) throw new Error('matter_not_found'); const now = new Date().toISOString(); const id = crypto.randomUUID(); const r2Key = input.content ? `filings/${input.tenantId}/${input.matterId}/${id}.txt` : undefined; if (input.content && r2Key) await bucket.put(r2Key, input.content, { httpMetadata: { contentType: 'text/plain' } }); const artifact: FilingArtifact = { id, tenantId: input.tenantId, matterId: input.matterId, kind: input.kind, status: 'DRAFT', r2Key, blockedReasons: [], gateEvidence: {}, createdAt: now, updatedAt: now }; await db.prepare('INSERT INTO filing_artifacts (id, tenant_id, matter_id, kind, status, r2_key, blocked_reasons_json, payload_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(id, artifact.tenantId, artifact.matterId, artifact.kind, artifact.status, artifact.r2Key ?? null, '[]', JSON.stringify(artifact), now, now).run(); return artifact; }
export async function listFilingArtifacts(db: D1Database, tenantId: string, matterId: string): Promise<FilingArtifact[]> { const rows = await db.prepare('SELECT payload_json FROM filing_artifacts WHERE tenant_id = ? AND matter_id = ? ORDER BY created_at ASC').bind(tenantId, matterId).all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as FilingArtifact); }
export async function getFilingArtifact(db: D1Database, tenantId: string, matterId: string, artifactId: string): Promise<FilingArtifact | null> { const row = await db.prepare('SELECT payload_json FROM filing_artifacts WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(artifactId, tenantId, matterId).first<{ payload_json: string }>(); return row ? JSON.parse(row.payload_json) as FilingArtifact : null; }
export async function listFilingGateEvents(db: D1Database, tenantId: string, matterId: string, artifactId: string): Promise<Array<Record<string, unknown>>> { const rows = await db.prepare('SELECT id, from_status, to_status, evidence_ids_json, blocked_reasons_json, reviewer, human_confirmed, created_at FROM filing_gate_events WHERE tenant_id = ? AND matter_id = ? AND artifact_id = ? ORDER BY id ASC').bind(tenantId, matterId, artifactId).all<Record<string, unknown>>(); return rows.results.map((row) => ({ ...row, evidenceIds: JSON.parse(String(row.evidence_ids_json)), blockedReasons: JSON.parse(String(row.blocked_reasons_json)), humanConfirmed: Boolean(row.human_confirmed) })); }
export async function advanceFilingArtifact(db: D1Database, tenantId: string, matterId: string, artifactId: string, nextStatus: FilingArtifact['status'], blockedReasons: string[], evidenceIds: string[], humanConfirmed: boolean, reviewer?: string): Promise<FilingArtifact> {
  const row = await db.prepare('SELECT payload_json FROM filing_artifacts WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(artifactId, tenantId, matterId).first<{ payload_json: string }>();
  if (!row) throw new Error('artifact_not_found_or_out_of_scope');
  const artifact = JSON.parse(row.payload_json) as FilingArtifact;
  const sequence: FilingArtifact['status'][] = ['DRAFT', 'FACT_CHECK', 'AUTHORITY_CHECK', 'RED_TEAM', 'BLUE_TEAM', 'PROCEDURAL_CHECK', 'EXHIBIT_CHECK', 'RELIEF_CHECK', 'HUMAN_REVIEW_REQUIRED', 'READY_TO_FILE'];
  const requiredGates: FilingGate[] = ['FACT_CHECK', 'AUTHORITY_CHECK', 'RED_TEAM', 'BLUE_TEAM', 'PROCEDURAL_CHECK', 'EXHIBIT_CHECK', 'RELIEF_CHECK', 'HUMAN_REVIEW_REQUIRED'];
  if (artifact.status === 'BLOCKED' && nextStatus !== 'DRAFT') throw new Error('blocked_artifact_requires_explicit_restart');
  if (nextStatus !== 'BLOCKED' && nextStatus !== 'READY_TO_FILE' && nextStatus !== 'DRAFT' && evidenceIds.length === 0) throw new Error('gate_evidence_required');
  if (nextStatus === 'READY_TO_FILE' && (!humanConfirmed || !reviewer || artifact.status !== 'HUMAN_REVIEW_REQUIRED')) throw new Error('human_review_gate_required');
  if (nextStatus === 'READY_TO_FILE' && !requiredGates.every((gate) => Array.isArray(artifact.gateEvidence?.[gate]) && artifact.gateEvidence[gate]!.length > 0)) throw new Error('all_review_gate_evidence_required');
  if (nextStatus !== 'BLOCKED' && nextStatus !== 'DRAFT') {
    const evidenceToVerify = nextStatus === 'READY_TO_FILE'
      ? Object.values(artifact.gateEvidence ?? {}).flat()
      : evidenceIds;
    await assertFilingEvidence(db, tenantId, matterId, evidenceToVerify);
  }
  if (nextStatus !== 'BLOCKED' && artifact.status !== 'BLOCKED' && nextStatus !== 'READY_TO_FILE' && sequence.indexOf(nextStatus) !== sequence.indexOf(artifact.status) + 1) throw new Error('invalid_filing_transition');
  const gateEvidence = nextStatus === 'DRAFT' ? {} : nextStatus !== 'BLOCKED' && nextStatus !== 'READY_TO_FILE' ? { ...(artifact.gateEvidence ?? {}), [nextStatus]: [...new Set(evidenceIds)] } : artifact.gateEvidence ?? {};
  const updated = { ...artifact, status: nextStatus, blockedReasons, gateEvidence, updatedAt: new Date().toISOString() };
  const statements = [
    db.prepare('UPDATE filing_artifacts SET status = ?, blocked_reasons_json = ?, payload_json = ?, updated_at = ? WHERE id = ? AND tenant_id = ? AND matter_id = ?').bind(updated.status, JSON.stringify(blockedReasons), JSON.stringify({ ...updated, reviewer: nextStatus === 'READY_TO_FILE' ? reviewer : undefined }), updated.updatedAt, artifactId, tenantId, matterId),
    db.prepare('INSERT INTO filing_gate_events (tenant_id, matter_id, artifact_id, from_status, to_status, evidence_ids_json, blocked_reasons_json, reviewer, human_confirmed) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(tenantId, matterId, artifactId, artifact.status, nextStatus, JSON.stringify(evidenceIds), JSON.stringify(blockedReasons), reviewer ?? null, humanConfirmed ? 1 : 0),
  ];
  await db.batch(statements);
  return updated;
}
export async function coordinateMatterEvent(ns: { idFromName(name: string): unknown; get(id: unknown): { fetch(input: string, init?: RequestInit): Promise<Response> } } | undefined, tenantId: string, matterId: string, event: unknown): Promise<void> { if (!ns) return; await ns.get(ns.idFromName(`matter:${tenantId}:${matterId}`)).fetch('https://matter-coordinator/event', { method: 'POST', body: JSON.stringify({ tenantId, matterId, event }), headers: { 'content-type': 'application/json' } }); }
export async function addAuthorityRecord(db: D1Database, input: Omit<AuthorityRecord, 'id' | 'status' | 'createdAt' | 'verifiedAt'> & { tenantId: string }): Promise<AuthorityRecord> { await assertSourceScope(db, input.tenantId, input.sourceId, input.judgeId); await assertMatterScope(db, input.tenantId, input.matterId, input.judgeId); const record: AuthorityRecord = { ...input, id: crypto.randomUUID(), status: 'UNVERIFIED', createdAt: new Date().toISOString() }; await db.prepare('INSERT INTO authority_records (id, tenant_id, judge_id, matter_id, name, citation, authority_type, court, year, proposition, source_id, status, created_at, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(record.id, record.tenantId, record.judgeId, record.matterId ?? null, record.name, record.citation, record.authorityType, record.court ?? null, record.year ?? null, record.proposition ?? null, record.sourceId ?? null, record.status, record.createdAt, JSON.stringify(record)).run(); return record; }
export async function listAuthorityRecords(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<AuthorityRecord[]> { const query = matterId ? db.prepare('SELECT payload_json FROM authority_records WHERE tenant_id = ? AND judge_id = ? AND (matter_id IS NULL OR matter_id = ?) ORDER BY created_at DESC').bind(tenantId, judgeId, matterId) : db.prepare('SELECT payload_json FROM authority_records WHERE tenant_id = ? AND judge_id = ? AND matter_id IS NULL ORDER BY created_at DESC').bind(tenantId, judgeId); const rows = await query.all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as AuthorityRecord); }
export async function listAuthorityEdges(db: D1Database, tenantId: string, judgeId: string, matterId?: string): Promise<AuthorityEdge[]> { const scope = matterId ? 'AND (a.matter_id IS NULL OR a.matter_id = ?) AND (b.matter_id IS NULL OR b.matter_id = ?)' : 'AND a.matter_id IS NULL AND b.matter_id IS NULL'; const query = matterId ? db.prepare(`SELECT e.payload_json FROM authority_edges e JOIN authority_records a ON a.id = e.from_authority_id AND a.tenant_id = e.tenant_id JOIN authority_records b ON b.id = e.to_authority_id AND b.tenant_id = e.tenant_id WHERE e.tenant_id = ? AND a.judge_id = ? AND b.judge_id = ? ${scope} ORDER BY e.created_at DESC`).bind(tenantId, judgeId, judgeId, matterId, matterId) : db.prepare(`SELECT e.payload_json FROM authority_edges e JOIN authority_records a ON a.id = e.from_authority_id AND a.tenant_id = e.tenant_id JOIN authority_records b ON b.id = e.to_authority_id AND b.tenant_id = e.tenant_id WHERE e.tenant_id = ? AND a.judge_id = ? AND b.judge_id = ? ${scope} ORDER BY e.created_at DESC`).bind(tenantId, judgeId, judgeId); const rows = await query.all<{ payload_json: string }>(); return rows.results.map((row) => JSON.parse(row.payload_json) as AuthorityEdge); }
export async function reviewAuthorityRecord(db: D1Database, tenantId: string, judgeId: string, input: { authorityId: string; reviewer: string; decision: AuthorityRecord['status']; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (!input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const row = await db.prepare('SELECT payload_json FROM authority_records WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(input.authorityId, tenantId, judgeId).first<{ payload_json: string }>(); if (!row) throw new Error('authority_not_found_or_out_of_scope'); const record = JSON.parse(row.payload_json) as AuthorityRecord; if (input.decision === 'VERIFIED') await assertSourceVerified(db, tenantId, record.sourceId, judgeId); record.status = input.decision; if (input.decision === 'VERIFIED') record.verifiedAt = new Date().toISOString(); await db.batch([db.prepare('UPDATE authority_records SET status = ?, verified_at = ?, payload_json = ? WHERE id = ? AND tenant_id = ? AND judge_id = ?').bind(record.status, record.verifiedAt ?? null, JSON.stringify(record), input.authorityId, tenantId, judgeId), db.prepare('INSERT INTO authority_review_events (id, tenant_id, authority_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (NULL, ?, ?, ?, ?, ?, ?, ?)').bind(tenantId, input.authorityId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function addAuthorityEdge(db: D1Database, input: Omit<AuthorityEdge, 'id' | 'status' | 'createdAt'> & { judgeId: string }): Promise<AuthorityEdge> { const rows = await db.prepare('SELECT id, judge_id, matter_id FROM authority_records WHERE id IN (?, ?) AND tenant_id = ?').bind(input.fromAuthorityId, input.toAuthorityId, input.tenantId).all<{ id: string; judge_id: string; matter_id: string | null }>(); if (rows.results.length !== 2 || rows.results.some((row) => row.judge_id !== input.judgeId) || rows.results[0]!.judge_id !== rows.results[1]!.judge_id || (rows.results[0]!.matter_id && rows.results[1]!.matter_id && rows.results[0]!.matter_id !== rows.results[1]!.matter_id)) throw new Error('authority_edge_out_of_scope'); await assertSourceScope(db, input.tenantId, input.sourceId, input.judgeId); const { judgeId: _judgeId, ...edgeInput } = input; const edge: AuthorityEdge = { ...edgeInput, id: crypto.randomUUID(), status: 'UNVERIFIED', createdAt: new Date().toISOString() }; await db.prepare('INSERT INTO authority_edges (id, tenant_id, from_authority_id, to_authority_id, relationship, evidence_note, source_id, status, created_at, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').bind(edge.id, edge.tenantId, edge.fromAuthorityId, edge.toAuthorityId, edge.relationship, edge.evidenceNote, edge.sourceId ?? null, edge.status, edge.createdAt, JSON.stringify(edge)).run(); return edge; }
export async function reviewAuthorityEdge(db: D1Database, tenantId: string, judgeId: string, input: { edgeId: string; reviewer: string; decision: 'VERIFIED' | 'DISPUTED'; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (!input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const row = await db.prepare('SELECT e.payload_json FROM authority_edges e JOIN authority_records a ON a.id = e.from_authority_id AND a.tenant_id = e.tenant_id JOIN authority_records b ON b.id = e.to_authority_id AND b.tenant_id = e.tenant_id WHERE e.id = ? AND e.tenant_id = ? AND a.judge_id = ? AND b.judge_id = ? AND (a.matter_id IS NULL OR b.matter_id IS NULL OR a.matter_id = b.matter_id)').bind(input.edgeId, tenantId, judgeId, judgeId).first<{ payload_json: string }>(); if (!row) throw new Error('authority_edge_not_found_or_out_of_scope'); const edge = JSON.parse(row.payload_json) as AuthorityEdge; if (input.decision === 'VERIFIED') await assertSourceVerified(db, tenantId, edge.sourceId, judgeId); edge.status = input.decision; await db.batch([db.prepare('UPDATE authority_edges SET status = ?, payload_json = ? WHERE id = ? AND tenant_id = ?').bind(edge.status, JSON.stringify(edge), input.edgeId, tenantId), db.prepare('INSERT INTO authority_edge_reviews (tenant_id, edge_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(tenantId, input.edgeId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function reviewJudgeIdentity(db: D1Database, tenantId: string, judgeId: string, input: { reviewer: string; decision: JudgeProfileIdentity['status']; notes: string; verificationSourceUrl?: string; verificationSourceHash?: string }): Promise<void> { if (input.decision !== 'NEEDS_VERIFICATION' && !input.verificationSourceUrl && !input.verificationSourceHash) throw new Error('verification_evidence_required'); const identity = await getJudgeIdentity(db, tenantId, judgeId); if (!identity) throw new Error('identity_not_found_or_out_of_scope'); identity.status = input.decision; if (input.decision === 'CURRENT') identity.lastVerified = new Date().toISOString(); await db.batch([db.prepare('UPDATE judge_profiles SET status = ?, last_verified = ?, payload_json = ? WHERE tenant_id = ? AND judge_id = ?').bind(identity.status, identity.lastVerified, JSON.stringify(identity), tenantId, judgeId), db.prepare('INSERT INTO judge_profile_reviews (tenant_id, judge_id, reviewer, decision, notes, verification_source_url, verification_source_hash) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(tenantId, judgeId, input.reviewer, input.decision, input.notes, input.verificationSourceUrl ?? null, input.verificationSourceHash ?? null)]); }
export async function listJudgeProfileReviews(db: D1Database, tenantId: string, judgeId: string): Promise<Array<Record<string, unknown>>> { const rows = await db.prepare('SELECT id, prediction_id, reviewer, decision, notes, verification_source_url, verification_source_hash, created_at FROM judge_profile_reviews WHERE tenant_id = ? AND judge_id = ? ORDER BY id ASC').bind(tenantId, judgeId).all<Record<string, unknown>>(); return rows.results; }
