import type { Argument, ClaimDigitalTwin } from '../../domain.ts';
import type { ChamberResult } from './types.ts';

export const ADVERSARIAL_ROUNDS = ['RED_OPENING','BLUE_OPENING','RED_REBUTTAL','BLUE_REBUTTAL','EVIDENCE_CHALLENGE','POLICY_AUTHORITY_CHALLENGE','LEGAL_PRECEDENT_CHALLENGE','TECHNICAL_XACTIMATE_CHALLENGE','DAMAGES_CHALLENGE'] as const;
export interface CourtRound { round:number; name:typeof ADVERSARIAL_ROUNDS[number]; issueIds:string[]; unresolved:string[]; completed:boolean; }
export interface WhiteCourtFinding { issueId:string; outcome:'RED_PREVAILS'|'BLUE_PREVAILS'|'RED_PARTIALLY_PREVAILS'|'BLUE_PARTIALLY_PREVAILS'|'BOTH_PARTIALLY_CORRECT'|'NEITHER_POSITION_PROVEN'|'INSUFFICIENT_EVIDENCE'|'LEGAL_QUESTION_REQUIRES_HUMAN_COUNSEL'|'TECHNICAL_QUESTION_REQUIRES_EXPERT'; scores:{factual:number;evidentiary:number;policy:number;legal:number;technical:number;mathematical:number}; rationale:string; dissent?:string; }
export interface AppellateResult { outcome:'AFFIRM'|'AFFIRM_WITH_MODIFICATION'|'REMAND_FOR_MORE_EVIDENCE'|'REMAND_FOR_POLICY_ANALYSIS'|'REMAND_FOR_CAUSATION'|'REMAND_FOR_PRICING'|'REVERSE'; reasons:string[]; independentReviewerRequired:true; }
export function runAdversarialRounds(arguments_:Argument[]):CourtRound[] { return ADVERSARIAL_ROUNDS.map((name,index)=>({round:index+1,name,issueIds:arguments_.map((issue)=>issue.issueId),unresolved:arguments_.filter((issue)=>issue.humanReview).map((issue)=>issue.issueId),completed:true})); }
export function adjudicateWhite(issue:Argument):WhiteCourtFinding { const scores={factual:issue.evidenceFor.length?60:0,evidentiary:issue.evidenceFor.length?60:0,policy:issue.policyAuthority.length?70:0,legal:issue.legalAuthority.length?70:0,technical:issue.technicalAuthority.length?70:0,mathematical:issue.financialImpact.claimedRcv !== undefined?60:0}; const minimum=Math.min(...Object.values(scores)); const outcome:WhiteCourtFinding['outcome']=minimum<30?'INSUFFICIENT_EVIDENCE':issue.carrierPosition&&issue.contractorPosition?'BOTH_PARTIALLY_CORRECT':'NEITHER_POSITION_PROVEN'; return {issueId:issue.issueId,outcome,scores,rationale:'Finding is limited to the submitted record; no missing policy, authority, causation, or technical fact is inferred.',dissent:outcome==='BOTH_PARTIALLY_CORRECT'?'Dissent: the missing upstream dependency may change the result.':undefined}; }
export function appellateReview(record:{twin:ClaimDigitalTwin; findings:WhiteCourtFinding[]; citationsVerified:boolean}):AppellateResult { const reasons:string[]=[]; if(!record.citationsVerified) reasons.push('citation verification is incomplete'); if(!record.twin.policy) reasons.push('policy is absent'); if(record.findings.some((finding)=>finding.outcome==='INSUFFICIENT_EVIDENCE')) reasons.push('material issue lacks sufficient evidence'); return {outcome:reasons.length?'REMAND_FOR_MORE_EVIDENCE':'AFFIRM',reasons,independentReviewerRequired:true}; }
export function chamber(name:ChamberResult['chamber'], findings:string[], evidenceRefs:string[]=[]):ChamberResult { return {chamber:name,findings,evidenceRefs,unresolved:findings.length?[]:['record contains no finding'],confidence:findings.length?60:0}; }
