import type { Evidence, Policy, PolicyProvision, Endorsement, EstimateLineItem, ConfidenceProfile, Argument, IssueDisposition } from '../../domain.ts';

export type CoverageStatus = 'COVERED_DIRECT_DAMAGE'|'COVERED_RESULTING_DAMAGE'|'COVERED_ACCESS_OPERATION'|'COVERED_DEPENDENT_OPERATION'|'COVERED_CODE_OPERATION'|'COVERED_SUBJECT_TO_LIMIT'|'COVERED_SUBJECT_TO_DEDUCTIBLE'|'COVERED_SUBJECT_TO_DEPRECIATION'|'NOT_COVERED'|'EXCLUDED'|'LIMITED'|'NOT_PROVEN'|'POLICY_AMBIGUOUS'|'LEGAL_AUTHORITY_CONFLICT'|'FACTUAL_CAUSATION_UNRESOLVED'|'CONDITION_PRECEDENT_ISSUE'|'REQUIRES_EXPERT_REVIEW'|'REQUIRES_LEGAL_REVIEW'|'COVERED_BUT_SCOPE_DISPUTED'|'COVERED_BUT_QUANTITY_DISPUTED'|'COVERED_BUT_PRICE_DISPUTED';
export type OperationType = 'DIRECT_DAMAGE_REPAIR'|'RESULTING_DAMAGE_REPAIR'|'ACCESS_OPERATION'|'DETACH_RESET'|'DEMOLITION'|'PROTECTION'|'TEMPORARY_REPAIR'|'EMERGENCY_MITIGATION'|'CODE_UPGRADE'|'MATCHING_OPERATION'|'DEPENDENT_OPERATION'|'FINISHING_OPERATION'|'CLEANING'|'CONTAMINATION_REMEDIATION'|'CONTENT_MANIPULATION'|'PROJECT_OVERHEAD'|'GENERAL_OVERHEAD'|'PROFIT'|'PERMIT'|'ENGINEERING'|'TESTING'|'UNRELATED_WORK'|'UPGRADE'|'MAINTENANCE';
export interface CompiledProvision { provisionId:string; form:string; edition:string; page:string; section:string; originalText:string; normalizedRule:Record<string,unknown>; exceptions:string[]; modifiedBy:string[]; supersedes:string[]; jurisdictionInterpretations:string[]; ambiguityFlags:string[]; citations:string[]; }
export interface EffectivePolicyVersion { policyId:string; asOfLossDate:string; provisionIds:string[]; appliedEndorsements:string[]; conflicts:string[]; status:'RESOLVED'|'CONFLICT'|'INCOMPLETE'; }
export interface AuthorityNode { authorityId:string; kind:'CONSTITUTION'|'STATUTE'|'REGULATION'|'STATE_SUPREME_CASE'|'STATE_APPELLATE_CASE'|'FEDERAL_CIRCUIT_CASE'|'FEDERAL_DISTRICT_CASE'|'TRIAL_CASE'|'BULLETIN'|'JURY_INSTRUCTION'|'BUILDING_CODE'|'SECONDARY'; jurisdiction:string; court?:string; date:string; precedentialStatus:string; publicationStatus:string; subsequentHistory:string[]; negativeTreatment:string[]; policyLanguage:string[]; proposition:string; factualSimilarity:string; citation:string; pinpoint?:string; source:string; verified:boolean; }
export interface AuthorityEdge { from:string; relation:'CONTROLS'|'INTERPRETS'|'LIMITS'|'DISTINGUISHES'|'OVERRULES'|'SUPERSEDES'|'CITES'|'CONFLICTS_WITH'|'PERSUASIVE_TO'|'NOT_APPLICABLE_TO'; to:string; }
export interface PrecedentMatch { authorityId:string; jurisdictionMatch:number; policyLanguageMatch:number; endorsementMatch:number; perilMatch:number; factualMatch:number; proceduralMatch:number; legalIssueMatch:number; precedentialWeight:number; currentValidity:number; score:number; classification:'CONTROLLING'|'PERSUASIVE'|'WEAK_ANALOGY'|'NOT_APPLICABLE'|'UNVERIFIED'; reasons:string[]; }
export interface BurdenResult { issue:string; partyWithBurden:'INSURED'|'CARRIER'|'CLAIMANT'|'CONTESTED'|'UNKNOWN'; standard:string; authority:string[]; satisfied:'YES'|'NO'|'UNDETERMINED'; confidence:number; }
export interface CoverageChain { operationId:string; xactimateLineId?:string; damageId:string; causeId:string; physicalDamageProven:boolean|null; insuringAgreement:string[]; coverageGrant:string[]; definitions:string[]; exclusions:string[]; exceptions:string[]; endorsements:string[]; conditions:string[]; limitations:string[]; legalAuthority:string[]; technicalNecessity:string[]; evidence:string[]; coverageStatus:CoverageStatus; necessityStatus:IssueDisposition; quantityStatus:IssueDisposition; pricingStatus:IssueDisposition; redTeam:Record<string,unknown>; blueTeam:Record<string,unknown>; whiteTeam:Record<string,unknown>; confidence:ConfidenceProfile; humanReview:boolean; }
export interface ArgumentNode { argumentId:string; party:'RED'|'BLUE'|'WHITE'; issue:string; proposition:string; factsReliedOn:string[]; evidenceReliedOn:string[]; policyReliedOn:string[]; lawReliedOn:string[]; technicalAuthority:string[]; counterarguments:string[]; rebuttals:string[]; weaknesses:string[]; confidence:number; }
export interface ArgumentEdge { from:string; relation:'SUPPORTS'|'CONTRADICTS'|'DISTINGUISHES'|'REBUTS'|'DEPENDS_ON'|'UNDERCUTS'; to:string; }
export interface ChamberResult { chamber:'FACTS'|'EVIDENCE'|'CAUSATION'|'POLICY'|'LAW'|'CONSTRUCTION'|'XACTIMATE'|'DAMAGES'|'ADJUDICATION'; findings:string[]; evidenceRefs:string[]; unresolved:string[]; confidence:number; }
