export type AuthorityType='STATE_CONSTITUTION'|'STATE_STATUTE'|'ADMINISTRATIVE_REGULATION'|'STATE_SUPREME_CASE'|'STATE_APPELLATE_CASE'|'FEDERAL_CIRCUIT_CASE'|'FEDERAL_DISTRICT_CASE'|'STATE_TRIAL_CASE'|'AGENCY_GUIDANCE'|'APPROVED_FORM'|'NAIC_MODEL'|'SECONDARY';
export type LegalIssueCode='MATCHING'|'LABOR_DEPRECIATION'|'APPRAISAL'|'PROMPT_PAYMENT'|'BAD_FAITH'|'ASSIGNMENT'|'ORDINANCE_LAW'|'CAUSATION'|'PROOF_OF_LOSS'|'ATTORNEY_FEES'|'CLAIMS_PRACTICES'|'LATE_NOTICE'|'LIMITATIONS';
export type VerificationStatus='UNVERIFIED'|'PARTIALLY_VERIFIED'|'VERIFIED'|'FAILED'|'SUPERSEDED';
export interface TemporalRange { validFrom:string; validTo:string|null; systemFrom:string; systemTo:string|null; }
export interface LegalAuthority { authorityId:string; jurisdiction:string; authorityType:AuthorityType; title:string; citation:string; section?:string; subsection?:string; court?:string; agency?:string; decisionDate?:string; officialSourceUrl:string; retrievedAt:string; contentHash:string; supersededBy?:string; amends:string[]; repeals:string[]; interprets:string[]; negativeTreatment:string[]; verificationStatus:VerificationStatus; }
export interface AuthorityVersion { authorityId:string; versionId:string; temporal:TemporalRange; operativeText:string; sourceSnapshotId:string; contentHash:string; verifiedAt?:string; }
export interface LegalProposition { propositionId:string; authorityId:string; issueCode:LegalIssueCode; jurisdiction:string; ruleText:string; normalizedRule:string; holdingOrDicta:'HOLDING'|'DICTA'|'UNKNOWN'; mandatoryOrPermissive:'MANDATORY'|'PERMISSIVE'|'UNKNOWN'; partyBearingBurden:string; standard:string; conditions:string[]; exceptions:string[]; remedies:string[]; policyLanguageDependency:string[]; factDependency:string[]; temporal:TemporalRange; pinpointCitation:string; verificationStatus:VerificationStatus; confidence:number; }
export type RuleOperator='EQUALS'|'NOT_EQUALS'|'IN'|'NOT_IN'|'GREATER_THAN'|'LESS_THAN'|'DATE_BEFORE'|'DATE_AFTER'|'EXISTS'|'NOT_EXISTS'|'CONTAINS'|'POLICY_HAS'|'FACT_PROVEN'|'AUTHORITY_CONTROLS';
export interface RuleCondition { field:string; operator:RuleOperator; value?:string|number|boolean|string[]; }
export interface RuleEffect { field:string; value:string|number|boolean; }
export interface CompiledLegalRule { ruleId:string; jurisdiction:string; issue:LegalIssueCode; validity:TemporalRange; priority:number; if:{all:RuleCondition[];any:RuleCondition[];not:RuleCondition[]}; then:{classification:string;effects:RuleEffect[]}; exceptions:RuleCondition[][]; authorityRefs:string[]; policyDependencies:string[]; factDependencies:string[]; confidence:number; humanReviewConditions:string[]; status:'DRAFT'|'SOURCE_VERIFIED'|'AUTHORITY_VERIFIED'|'RED_BLUE_REVIEWED'|'WHITE_APPROVED'|'APPELLATE_VERIFIED'|'HUMAN_APPROVED_IF_REQUIRED'|'PRODUCTION'|'DEPRECATED'|'SUPERSEDED'; }
export interface LegalConflict { conflictId:string; jurisdiction:string; issue:LegalIssueCode; authorityA:string; authorityB:string; conflictType:'COURT_SPLIT'|'STATUTE_CASE_CONFLICT'|'REGULATION_CASE_CONFLICT'|'TEMPORAL_CONFLICT'|'POLICY_LANGUAGE_CONFLICT'|'FEDERAL_STATE_PREDICTION_CONFLICT'; reason:string; potentialResolution:string; controllingCandidate?:string; confidence:number; humanReview:true; }
export interface JurisdictionProfile { code:string; name:string; level:'STATE'|'DISTRICT'; federalCircuit?:string; sourceRegistryStatus:'NOT_STARTED'|'PARTIAL'|'VERIFIED'; supportedIssues:LegalIssueCode[]; lastVerified?:string; }
export interface SourceRegistry { jurisdiction:string; legislature:string[]; administrativeCode:string[]; supremeCourt:string[]; appellateCourts:string[]; insuranceDepartment:string[]; approvedForms:string[]; bulletins:string[]; consumerGuidance:string[]; federalCircuit?:string; federalDistricts:string[]; lastVerified?:string; }
export interface ClaimLegalContext { claimId:string; jurisdictionCandidates:string[]; resolvedJurisdiction:string|null; policyEffectiveDate:string|null; policyExpirationDate:string|null; dateOfLoss:string; claimReportedDate?:string; inspectionDate?:string; denialDate?:string; paymentDate?:string; suitFiledDate?:string; issue:LegalIssueCode; policyProvision?:string; materialFacts:Record<string,unknown>; }
export interface LegalAuthorityPackage { issue:LegalIssueCode; jurisdiction:string; asOf:string; rules:CompiledLegalRule[]; propositions:LegalProposition[]; controllingAuthorities:LegalAuthority[]; persuasiveAuthorities:LegalAuthority[]; conflicts:LegalConflict[]; humanReview:boolean; confidence:ConfidenceVector; }
export interface LegalDecision { decisionId:string; context:ClaimLegalContext; status:'RULE_UNRESOLVED'|'PROVISIONAL'|'HUMAN_REVIEW_REQUIRED'|'PRODUCTION'; package:LegalAuthorityPackage; rationale:string; createdAt:string; }
export interface CitationVerification { citationId:string; authorityId:string; source:string; exists:'YES'|'NO'|'UNKNOWN'; supports:'YES'|'NO'|'UNKNOWN'; temporal:'YES'|'NO'|'UNKNOWN'; jurisdiction:'YES'|'NO'|'UNKNOWN'; pinpoint?:string; status:'VERIFIED'|'PARTIALLY_VERIFIED'|'FAILED'; notes:string[]; }
export interface ConfidenceVector { source:number; citation:number; authority:number; temporal:number; jurisdiction:number; policyMatch:number; factMatch:number; precedent:number; compilation:number; overallUse:number; }
