/**
 * Federal Pleading Engine - Constitutional / Civil Rights Claims (42 U.S.C. § 1983)
 *
 * Claim metadata for § 1983 constitutional torts, Monell municipal liability,
 * § 1985 conspiracy, and § 1986 failure-to-prevent claims.
 */

import { ClaimMetadata } from '../schema';

export const CONSTITUTIONAL_CLAIMS: Record<string, ClaimMetadata> = {
  '1983_first_amendment_retaliation': {
    name: 'First Amendment Retaliation (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. I',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity - right not clearly established',
      'Same decision regardless of speech',
      'Speech not on matter of public concern',
      'Speech pursuant to official duties (Garcetti)',
      'Disruption to government operations',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_first_amendment_speech_restriction': {
    name: 'First Amendment Speech Restriction (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. I',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'Viewpoint-neutral time/place/manner restriction',
      'Content-neutral regulation',
      'Compelling government interest (strict scrutiny)',
      'Traditional public forum vs limited forum',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_fourth_false_arrest': {
    name: 'Fourth Amendment False Arrest (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. IV',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'Probable cause existed',
      'Arguable probable cause',
      'Good faith reliance on warrant',
      'Consent to encounter',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_fourth_unlawful_search_seizure': {
    name: 'Fourth Amendment Unlawful Search/Seizure (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. IV',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'Valid warrant',
      'Consent',
      'Exigent circumstances',
      'Plain view doctrine',
      'Search incident to arrest',
      'Automobile exception',
      'Terry stop justified',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_fourth_excessive_force': {
    name: 'Fourth Amendment Excessive Force (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. IV',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity - no clearly established right',
      'Force objectively reasonable under Graham v. Connor',
      'Severity of crime at issue',
      'Immediate threat to officers/others',
      'Active resistance or flight',
      'Tense/rapidly evolving situation',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_fourteenth_procedural_due_process': {
    name: 'Fourteenth Amendment Procedural Due Process (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. XIV',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'No protected property/liberty interest',
      'Adequate post-deprivation remedies',
      'Random and unauthorized act (Parratt doctrine)',
      'Adequate pre-deprivation process provided',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_fourteenth_substantive_due_process': {
    name: 'Fourteenth Amendment Substantive Due Process (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. XIV',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'Conduct does not shock the conscience',
      'Explicit textual source in Constitution (use that instead)',
      'Rational basis for government action',
      'No fundamental right implicated',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_fourteenth_equal_protection': {
    name: 'Fourteenth Amendment Equal Protection (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. XIV',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'Rational basis for classification',
      'No discriminatory intent',
      'Similarly situated comparators not actually similar',
      'Legitimate non-discriminatory reason',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1983_monell_municipal_liability': {
    name: 'Monell Municipal Liability (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; Monell v. Dep\'t of Social Servs., 436 U.S. 658 (1978)',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: [],  // Municipalities cannot claim qualified immunity
    typicalDefenses: [
      'No underlying constitutional violation',
      'No official policy or custom',
      'Policy did not cause the violation',
      'No final policymaker involvement',
      'No deliberate indifference to known pattern',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1985_conspiracy': {
    name: 'Conspiracy to Deprive Rights (42 U.S.C. § 1985)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1985(3)',
    sourceType: 'statute',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'No class-based animus',
      'No agreement between defendants',
      'No overt act in furtherance',
      'Intracorporate conspiracy doctrine',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },

  '1986_failure_to_prevent': {
    name: 'Failure to Prevent Conspiracy (42 U.S.C. § 1986)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1986',
    sourceType: 'statute',
    heightenedPleading: false,
    exhaustionRequired: false,
    exhaustionType: null,
    immunities: ['qualified'],
    typicalDefenses: [
      'No underlying § 1985 conspiracy',
      'No knowledge of conspiracy',
      'No power to prevent',
      'Reasonable diligence used',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: '1 year from commission of wrong',
  },

  '1983_eighth_deliberate_indifference': {
    name: 'Eighth Amendment Deliberate Indifference (§ 1983)',
    category: 'constitutional_civil_rights',
    source: '42 U.S.C. § 1983; U.S. Const. amend. VIII; Estelle v. Gamble, 429 U.S. 97 (1976)',
    sourceType: 'constitutional',
    heightenedPleading: false,
    exhaustionRequired: true,  // PLRA exhaustion for prisoners
    exhaustionType: 'plra',
    immunities: ['qualified'],
    typicalDefenses: [
      'Qualified immunity',
      'Mere negligence (not deliberate indifference)',
      'No subjective knowledge of substantial risk',
      'Reasonable response to risk',
      'PLRA exhaustion not completed',
    ],
    jurisdiction: 'federal_question',
    statuteOfLimitations: 'State personal injury SOL (typically 2-4 years)',
  },
};
