import test from 'node:test';
import assert from 'node:assert/strict';
import { compileProvision, resolveEndorsements } from '../src/claims/adjudication/policy.ts';
import { CoverageAuthorityEngine } from '../src/claims/adjudication/coverage.ts';
import { LegalAuthorityGraph, matchPrecedent, determineBurden } from '../src/claims/adjudication/authority.ts';
import { decomposeLine } from '../src/claims/xactimate/evidence.ts';
import { requireHumanReview } from '../src/claims/adjudication/governance.ts';
import { verifyCitation } from '../src/claims/evidence/verification.ts';
import type { Policy } from '../src/domain.ts';

const policy:Policy={policyId:'POL-1',policyType:'HO-3',carrier:'C',period:'2026',declarationsDocId:'D-DECL',forms:[],provisions:[{provisionId:'P-1',kind:'GRANT',text:'Covered property',docId:'D-POL',page:'14'}],endorsements:[{endorsementId:'E-1',identifier:'END-1',editionDate:'2026-01-01',docId:'D-E',modifies:['P-1'],pageRefs:['1']}],status:'KNOWN'};
test('policy compiler retains original text and provenance',()=>{const compiled=compileProvision(policy.provisions[0]);assert.equal(compiled.originalText,'Covered property');assert.equal(compiled.page,'14');});
test('endorsement resolver reports conflicting modification graph',()=>{const result=resolveEndorsements({...policy,endorsements:[...policy.endorsements,{endorsementId:'E-2',identifier:'END-2',editionDate:'2026-01-02',docId:'D-E2',modifies:['P-1'],pageRefs:['1']}]},'2026-02-01');assert.equal(result.status,'CONFLICT');assert.equal(result.conflicts.length,1);});
test('coverage authority blocks missing evidence and policy',()=>{const result=new CoverageAuthorityEngine().evaluate({operationId:'OP-1',damageId:'D-1',causeId:'C-1',physicalDamageProven:null,insuringAgreement:[],coverageGrant:[],definitions:[],exclusions:[],exceptions:[],endorsements:[],conditions:[],limitations:[],legalAuthority:[],technicalNecessity:[],evidence:[],necessityStatus:'MISSING',quantityStatus:'MISSING',pricingStatus:'MISSING',redTeam:{},blueTeam:{},whiteTeam:{},confidence:{fact:0,policy:0,legal:0,causation:0,scope:0,price:0,overall:'UNDETERMINED'},humanReview:false});assert.equal(result.coverageStatus,'NOT_PROVEN');assert.equal(result.humanReview,true);});
test('authority graph rejects dangling edges and weak policy matches are not controlling',()=>{const graph=new LegalAuthorityGraph();graph.addNode({authorityId:'A-1',kind:'STATE_APPELLATE_CASE',jurisdiction:'TX',date:'2020',precedentialStatus:'binding',publicationStatus:'published',subsequentHistory:[],negativeTreatment:[],policyLanguage:['HO-3 water'],proposition:'water issue',factualSimilarity:'low',citation:'1 S.W.3d 1',source:'https://example.test',verified:true});assert.throws(()=>graph.addEdge({from:'A-1',relation:'CITES',to:'missing'}));const match=matchPrecedent(graph.nodes.get('A-1')!,{jurisdiction:'TX',policyLanguage:'different form',issue:'wind'});assert.notEqual(match.classification,'CONTROLLING');});
test('burden engine refuses universal burden assumptions',()=>{assert.equal(determineBurden('exclusion','TX').partyWithBurden,'UNKNOWN');});
test('xactimate evidence treats price as evidence and requires source for necessity',()=>{const output=decomposeLine({lineId:'L-1',estimateId:'E-1',room:'Kitchen',trade:'Water',category:'WTR',selector:'ABC',description:'air mover',activity:'rent',quantity:2,unit:'EA',unitPrice:50,rcv:100,depreciation:0,acv:100,tax:0,op:0,evidenceRefs:[],policyRefs:[],legalRefs:[],dependencies:[],flags:[],confidence:'UNDETERMINED'},{labor:20,material:0,equipment:80});assert.equal(output.whyRequired,'REQUIRES_SOURCE');assert.equal(output.breakdown.equipment,80);});
test('governance escalates high-risk decisions',()=>{assert.deepEqual(requireHumanReview({policyAmbiguous:false,legalConflict:true,fraudIndicator:false,structuralSafety:false,exposure:0,litigationPending:false}).required,true);});
test('unverified citations are blocked',()=>{assert.equal(verifyCitation({claimId:'C-1',jurisdiction:'TX',authorityId:'A-1',citation:'1 S.W.3d 1',source:'https://example.test',verified:false}).status,'BLOCKED');});
