import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveJurisdiction, validateAuthorityForJurisdiction } from '../src/claims/adjudication/jurisdiction.ts';
import { buildCausationGraph, validateCausationGraph } from '../src/claims/causation/graphs.ts';
import { auditDependencies } from '../src/claims/building/dependencies.ts';
import { runAdversarialRounds, adjudicateWhite, appellateReview } from '../src/claims/adjudication/court.ts';
import { assembleReport } from '../src/claims/report.ts';
import type { Argument, ClaimDigitalTwin } from '../src/domain.ts';

const argument:Argument={issueId:'I-1',claimId:'C-1',issueType:'EQUIPMENT',description:'equipment count',contractorPosition:'six units supported',carrierPosition:'two units supported',policyAuthority:['P-1'],legalAuthority:['A-1'],technicalAuthority:['T-1'],evidenceFor:['E-1'],evidenceAgainst:[],redTeam:{position:'',strongestAttack:'',survives:null,evidenceRefs:['E-1']},blueTeam:{position:'',strongestAttack:'',survives:null,evidenceRefs:[]},financialImpact:{claimedRcv:600},confidence:{fact:60,policy:60,legal:60,causation:60,scope:60,price:60,overall:'MEDIUM'},missingInformation:[],humanReview:true};
test('jurisdiction resolver refuses silent state conflict',()=>{const result=resolveJurisdiction({propertyState:'TX',policyState:'FL'});assert.equal(result.status,'AMBIGUOUS');assert.ok(result.confidence<50);});
test('authority validation blocks unverified or unresolved jurisdiction',()=>{const result=validateAuthorityForJurisdiction({authorityId:'A',kind:'STATUTE',jurisdiction:'TX',date:'2026',precedentialStatus:'binding',publicationStatus:'published',subsequentHistory:[],negativeTreatment:[],policyLanguage:[],proposition:'',factualSimilarity:'',citation:'',source:'',verified:false},{state:'TX',status:'AMBIGUOUS',basis:[],confidence:20});assert.ok(result.length>=3);});
test('causation graph requires evidence on non-event nodes',()=>{const graph=buildCausationGraph({event:'water loss',force:'supply line',mechanism:'migration',condition:'wet drywall',damage:'drywall damage',remediation:'drying',repair:'replacement',evidenceRefs:[]});assert.ok(validateCausationGraph(graph).length>0);});
test('dependency audit identifies missing prerequisites and duplicate operations',()=>{const findings=auditDependencies([{operationId:'O-1',name:'remove drywall',prerequisites:['O-0'],downstream:[],evidenceRefs:[]},{operationId:'O-2',name:'Remove Drywall',prerequisites:[],downstream:[],evidenceRefs:[]}]);assert.equal(findings[0].status,'INCOMPLETE');assert.deepEqual(findings[0].duplicateCandidates,['O-2']);});
test('adjudication executes all required rebuttal rounds',()=>{const rounds=runAdversarialRounds([argument]);assert.equal(rounds.length,9);assert.ok(rounds.every((round)=>round.completed));const finding=adjudicateWhite(argument);assert.equal(finding.outcome,'BOTH_PARTIALLY_CORRECT');});
test('appellate chamber remands incomplete records',()=>{const twin={claim:{claimId:'C-1',carrier:'C',insured:'I',property:{propertyId:'P',address:'',state:'TX',rooms:[],status:'UNKNOWN'},lossDate:'',reportedDate:'',causeOfLoss:'',policyId:'',policyPeriod:'',parties:[],documents:[],timeline:[],status:'UNKNOWN'},evidence:[],causes:[],damages:[],estimates:[],invoices:[],equipment:[],moisture:[],arguments:[argument],status:'UNKNOWN'} as ClaimDigitalTwin;const appeal=appellateReview({twin,findings:[adjudicateWhite(argument)],citationsVerified:false});assert.equal(appeal.outcome,'REMAND_FOR_MORE_EVIDENCE');const report=assembleReport(twin,[adjudicateWhite(argument)],appeal);assert.equal(report.status,'HUMAN_REVIEW_REQUIRED');});
